- system/src/Grav/Common/Assets.php
Use md5 from content for discard multiple iterance.
> Add inline assets priority

- composer.json
- system/tests/Grav/TestCase.php
- system/tests/bootstrap.php
- system/tests/phpunit.xml
I think this could serve as a base for unit testing nicely.
First step to closing #56
> PHPUnit testing introduced

- system/src/Grav/Common/User/User.php
Reverts getgrav/grav#124 (should have been against develop)
> Revert "Replace constant with streams. (need for multisite)."

- system/config/streams.yaml
- system/src/Grav/Common/Config/Config.php
- system/src/Grav/Common/Page/Media.php
- system/src/Grav/Common/Page/Medium.php
- Removed unused variables.
- Add missed phpdoc params.
- Update constants with locator.
> Bug fixes phpdoc/missed vars/locator.

- web.config
The system/assets folder is accessible except for .txt .md .html .yaml .php .twig .sh .bat files.
> Updated web.config  - Assets accesible

- nginx.conf
Ensure images are served as static files when using Nginx
> Serve images as static files

- README.md
Two minor grammar changes:
- Corrected "principals" to be "principles"
- Corrected verb tense of "has been designed" to match the rest of the sentence
> README.md grammar changes

- system/src/Grav/Common/GPM/GPM.php
$this->grav is not what we expect here. Got a fatal error on `$ bin/gpm` execution
> Correctly instantiate the Inflector

- nginx.conf
Added conf sample settings for running grav in a sub directory, on nginx
> added conf settings for running grav in sud dir, on nginx

- system/blueprints/pages/default.yaml
Refs https://github.com/getgrav/grav-plugin-admin/issues/122
> Put autofocus on page title

- .htaccess
- htaccess.txt
last try...this one should be correct
> .htaccess hardening

- system/blueprints/pages/default.yaml
- system/blueprints/pages/modular_raw.yaml
- system/blueprints/pages/raw.yaml
- system/src/Grav/Common/Twig/TwigExtension.php
- Renamed `uploads` form field to `pagemedia` in the pages blueprints
- Adds the `string` twig function that renders a variable as a string also if it's an array
> Work related to the Form plugin

- nginx.conf
File was a bit of a mess in general, regarding indentation and whitespace (tabs and spaces were used in the same line multiple times, for example).
> nginx.conf: cosmetic fixes

- system/src/Grav/Console/Cli/NewUserCommand.php
grav newuser was setting password to null irrespective of what was entered at the console
> Fix bug in newuser command

- system/src/Grav/Common/Page/Medium/AudioMedium.php
- system/src/Grav/Common/Page/Medium/MediumFactory.php
This is the first time I submit a pull request. I hope I'm doing it right.
> New Audio Medium added

- system/src/Grav/Common/Page/Medium/ImageMedium.php
Quick fix for the chaining of sizes and derivatives, so the order does not matter.
> Fix chaining for sizes and derivatives

- system/src/Grav/Common/Data/Blueprint.php
Problem presented in https://github.com/getgrav/grav-plugin-admin/issues/187.
Doing a PR since I'm not sure it's the best place to intercept this issue
> Fix saving array fields

- system/src/Grav/Common/Themes.php
This PR implements a better way to support theme inheritance and fixes some problems with the PR #353. It can now handle all flavours of setting up the child theme stream (`prefixes` and `paths` as well), it only loads the `languages.yaml` into the system, which really exists, it applies a `array_replace_recursive` only once now and it degrades gracefully, if the language file in the child theme/in the parent theme or no file is found.
Further it addresses #357 (Theme language files not working) and fixed it (implements it), too.
> Improved theme inheritance to support all kinds of streams

- system/languages/nl.yaml
My first pull request. Please let me know if this is the correct way to do this.
> Add dutch language file

- system/src/Grav/Common/Data/Validation.php
This PR addresses the changes mentioned in https://github.com/getgrav/grav-plugin-form/issues/12
> Addresses # 12 (form-plugin) Trim fields before validation

- system/languages/tr.yaml
> added "Turkish" language

- system/src/Grav/Common/Data/Validation.php
- system/src/Grav/Common/Errors/Errors.php
- system/src/Grav/Common/GPM/Local/AbstractPackageCollection.php
- system/src/Grav/Common/GPM/Remote/AbstractPackageCollection.php
- system/src/Grav/Common/Markdown/ParsedownGravTrait.php
- system/src/Grav/Common/Page/Media.php
- system/src/Grav/Common/Page/Medium/AudioMedium.php
- system/src/Grav/Common/Page/Medium/ImageFile.php
- system/src/Grav/Common/Page/Medium/ImageMedium.php
- system/src/Grav/Common/Page/Medium/VideoMedium.php
- system/src/Grav/Common/Plugins.php
- system/src/Grav/Common/Twig/Twig.php
- system/src/Grav/Common/Twig/TwigEnvironment.php
- system/src/Grav/Common/Uri.php
- system/src/Grav/Console/Cli/NewUserCommand.php
- system/src/Grav/Console/Gpm/UninstallCommand.php
removing duplicate key from an array and using relative base class name.
removing unused 'use' statements.
> remove duplicate key

- system/languages/en.yaml
These will need to be translated into other languages.
> Added form validation translations

- system/languages/hu.yaml
Tweaked translation for 'ago' - sounds less weird.
> Updated system/languages/hu.yaml

- system/src/Grav/Common/Twig/TwigExtension.php
- system/src/Grav/Common/Utils.php
Ex. WEEK_PLURAL, WEEK_PLURAL_MORE_THAN_TWO
Refs https://github.com/getgrav/grav/issues/471
> Handle languages that support _PLURAL_MORE_THAN_TWO

- system/src/Grav/Common/GPM/Response.php
- system/src/Grav/Common/Utils.php
Refs http://getgrav.org/forum#!/getgrav/general:set-time-limit-problems
> Include set_time_limit in a try/catch

- web.config
web.config now correctly allows for static files inside vendor folder, just like .htaccess
> Web.config update

- system/languages/en.yaml
- system/languages/es.yaml
- system/src/Grav/Common/Data/Blueprint.php
Adding language string for MISSING_REQUIRED_FIELD in checkRequired
Adding translation for new string in en.yaml
Adding es.yaml
> Adding language string for MISSING_REQUIRED_FIELD

- system/src/Grav/Common/Markdown/ParsedownGravTrait.php
- system/src/Grav/Common/Page/Medium/ImageMedium.php
In-progress PR to fix #544 
WIP, do not merge yet
> Fix orientation for images added via twig

- system/src/Grav/Common/GPM/GPM.php
Previously it listed four times `PHP Warning:  Invalid argument
supplied for foreach()...`, now it fails with an error message
> Improve error when trying to install a plugin/theme from the command line and GPM is unreachable

- system/src/Grav/Common/Page/Page.php
- system/src/Grav/Common/Page/Pages.php
> The date for the last update of a page that is modular is the update time of the module that was last modified

- composer.json
> Update Whoops to latest

- system/src/Grav/Common/Page/Page.php
> Remove any URL extension for the home link

- composer.json
Windows is dumb... gotta use those backslashes
> Add composer test command for windows

- system/languages/ja.yaml
Translation en.yaml to Japanese.
Add system/languages/ja.yaml
> Add Ja language file.

- system/src/Grav/Common/Twig/TwigExtension.php
- tests/unit/Grav/Common/InflectorTest.php
- tests/unit/Grav/Common/Twig/TwigExtensionTest.php
Close as you need tests. If closed I'll create another pull
~Cheers :sparkles:
> Adding Tests - On going

- system/defines.php
- system/src/Grav/Common/GPM/Common/Package.php
- system/src/Grav/Common/GPM/GPM.php
- system/src/Grav/Common/GPM/Remote/Plugins.php
- system/src/Grav/Common/GPM/Remote/Themes.php
- system/src/Grav/Console/Cli/BackupCommand.php
- system/src/Grav/Console/Cli/CleanCommand.php
- system/src/Grav/Console/Cli/ComposerCommand.php
- system/src/Grav/Console/Cli/NewProjectCommand.php
- system/src/Grav/Console/Cli/SandboxCommand.php
- system/src/Grav/Console/ConsoleCommand.php
- system/src/Grav/Console/Gpm/InfoCommand.php
- system/src/Grav/Console/Gpm/InstallCommand.php
- system/src/Grav/Console/Gpm/SelfupgradeCommand.php
- system/src/Grav/Console/Gpm/UninstallCommand.php
- system/src/Grav/Console/Gpm/UpdateCommand.php
- system/src/Grav/Console/Gpm/VersionCommand.php
- tests/unit/Grav/Common/InflectorTest.php
- tests/unit/Grav/Console/Gpm/InstallCommandTest.php
Work in progress. Do not merge.
Add dependencies versions handling to the GPM.
> WIP - Versions in dependencies

- webserver-configs/Caddyfile
Now /sitemap.xml or blog.rss or /info.php and so on are working also the evil regex is removed.
> Updating Caddyfile

- system/src/Grav/Common/Page/Pages.php
Allow page blueprints in plugins. Also invert order of loading templates, themes load last and have the "final word". Both on templates and in blueprints.
Cache everything if cache is enabled.
Example usage in a plugin:
```php
<?php
class MyPlugin extends Plugin
{
/* ... */
/**
* @return array
*/
public static function getSubscribedEvents()
{
return [
'onGetPageBlueprints'     => ['onGetPageBlueprints', 0],
'onGetPageTemplates'      => ['onGetPageTemplates', 0],
];
}
/* ... */
/**
* Add page blueprints
*
* @param Event $event
*/
public function onGetPageBlueprints(Event $event)
{
/** @var Types $types */
$types = $event->types;
$types->scanBlueprints('plugins://myplugin/blueprints/pages/');
}
/**
* Add page template types.
*
* @param Event $event
*/
public function …
```
> Allow page blueprints in plugins

- system/src/Grav/Common/GPM/GPM.php
- system/src/Grav/Console/Gpm/UpdateCommand.php
Hello,
This PR add options to update only plugins or themes when you 're running bin/gpm update.
Only plugins : bin/gpm update --plugins
Only themes : bin/gpm update --themes
PR Idea from issue https://github.com/getgrav/grav/issues/892, when PR merged fixes https://github.com/getgrav/grav/issues/892
PS : I don't know codeception, and there is no command Test, so I don't write UpdateCommandTest.
Bye
> Feature/more options gpm #892

- system/src/Grav/Common/Utils.php
> Cache images loaded from the route (when cache is enabled)

- CHANGELOG.md
- system/blueprints/config/system.yaml
- system/config/system.yaml
- system/src/Grav/Common/Cache.php
When a socket path is specified it should be used and by default host port with the default values.
> Added possiblity to connect to redis via a unix socket

- system/src/Grav/Common/Language/LanguageCodes.php
set the name and native name for these two.
(fr-FR and fr-CA)
> Add 2 new language values for French

- CHANGELOG.md
- system/src/Grav/Common/Page/Page.php
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer )
> spelling fixes

- CHANGELOG.md
- composer.lock
- system/blueprints/config/system.yaml
- system/config/system.yaml
- system/src/Grav/Common/Cache.php
- system/src/Grav/Common/Uri.php
- system/src/Grav/Console/ConsoleTrait.php
A fix for CLI to better integrate with non-volatile cache drivers: https://github.com/getgrav/grav/issues/1293
> Fixes to allow not just ‘default/file’ cache in CLI

- system/src/Grav/Common/Config/CompiledLanguages.php
- system/src/Grav/Common/Debugger.php
- system/src/Grav/Common/GPM/Upgrader.php
- system/src/Grav/Common/Helpers/Excerpts.php
- system/src/Grav/Common/Page/Medium/Medium.php
- system/src/Grav/Common/Processors/ProcessorBase.php
- system/src/Grav/Common/Taxonomy.php
- system/src/Grav/Console/Gpm/InfoCommand.php
- system/src/Grav/Console/Gpm/InstallCommand.php
- system/src/Grav/Console/Gpm/SelfupgradeCommand.php
- system/src/Grav/Console/Gpm/UpdateCommand.php
> Misc fixes to classes (type hinting, return types, missing variables...)

- system/src/Grav/Common/GPM/GPM.php
- system/src/Grav/Common/GPM/Response.php
- system/src/Grav/Console/Gpm/DirectInstallCommand.php
This work is required in order to add direct-install to admin
> Initial work to genericize direct-install

- system/src/Grav/Console/Gpm/DirectInstallCommand.php
- system/src/Grav/Console/Gpm/InstallCommand.php
To help user that need to install specific version of a package.
So far it wasn't absolutely clear how to achieve and some
users ended up asking for help or opening issues asking
for the feature.
> [#1200] Clarified `install` and `direct-install`

- system/src/Grav/Common/GPM/GPM.php
> Fix typo in GPM.php

- system/src/Grav/Common/Page/Page.php
Attempt to resolve this issue. Please check as I am not familiar enough with grav codebase to be confident.
> process_twig and frontmatter.yaml

- system/src/Grav/Common/Twig/TwigExtension.php
Fixes a bug when returning nicetime
> Fix undeclared variable $difference

- system/src/Grav/Common/Utils.php
* `contains()`: allow $needle to be an array just like in `startsWith()` and `endsWith()`
* Add some checks and casting to avoid possible notices
* Some minor code optimizations, use simpler code
* Use more strict comparisons
* Fix broken multi-part uploads in Windows (open file in binary mode)
> Clean up Utils class with minor fixes

- system/src/Grav/Common/GPM/Installer.php
Zip errors not really helpful, this provides more details
> Added more detailed error handling

- tests/unit/Grav/Common/AssetsTest.php
> Use dedicated PHPUnit assertions

- system/src/Grav/Console/Cli/SchedulerCommand.php
> Scheduler Fallback for never run and Windows

- system/src/Grav/Common/Browser.php
More information:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT
Used in:
https://github.com/getgrav/grav-plugin-admin/pull/1586
> add do not track header detection

- system/src/Grav/Common/Markdown/ParsedownGravTrait.php
This will allow plugins hooking this event to mergeConfig.
Fix #2412
> Add the page to the onMarkdownInitialized event.

- webserver-configs/nginx-ddev-site.conf
Updated nginx-ddev-site.conf for the newest version of ddev.
Addresses local ddev health check and 'Invalid AJAX Response' error.
> Updated for latest ddev version

- webserver-configs/lighttpd.conf
Just plain doesn't work without this!  Was probably omitted in error.
> Fix rewrite rule for lighttpd config

- system/src/Grav/Common/Page/Page.php
As I am not a developer somebody should review the change.
> Truncator: encoding problems solves #2154

- .travis.yml
php 7.4 is already released, so let's test it
> [travis] add php 7.4 to test

- CHANGELOG.md
> Fixed Link to XSS Security Docs

- system/languages/de.yaml
> Add german translations for GRAV.YES and GRAV.NO

- system/src/Grav/Common/Assets.php
- system/src/Grav/Common/Assets/Traits/TestingAssetsTrait.php
> Fix #2781 asset manager pipeline order

- index.php
Fixes #3399 by checking an additional ENV variable
> Fixes issue with Symfony local server detection

- system/config/media.yaml
Recommended by whatwg and draft-ietf-dispatch-javascript-mjs-09 (obsoletes RFC4329)
> Change mime-type to text/javascript

- index.php
> Merge index exceptions with same handling

- .github/workflows/tests.yaml
now released https://www.php.net/releases/8.2/en.php
> add php 8.2 to test

- system/blueprints/config/system.yaml
Already removed in commit ba2c37c2163edd7bcc6de753e18eba302ffdda75
> Remove outdated setting `xcache`

- .github/workflows/tests.yaml
https://www.php.net/releases/8.3/en.php
> add php 8.3 to test

- system/src/Grav/Framework/Flex/FlexCollection.php
- system/src/Grav/Framework/Flex/FlexObject.php
These comments break the json output.
Tired of commenting them every time after Grav update 😄
> Annoying output comments fix for json Flex

- system/src/Grav/Console/Application/CommandLoader/PluginCommandLoader.php
Adds aliases as possible commands during lookup
> Fix for #3164. Adds aliases as possible commands during lookup

- SECURITY.md
I really enjoyed using this project, nice work! Caught a couple of typos in the SECURITY.md though 😛
> Update SECURITY.md, fix typo(s)
