system/src/Grav/Common/Assets.php
system/src/Grav/Common/Page/Page.php

Dear Andy,
according to the recent forum post about adjusting summary lengths in Grav, I realized that there is no easy switch to easily enable or disable truncationation of summary contents. I think it is better to let the user decide, whether he or she wants a short version of his/her articles shown on frontpage or not.
Further I noticed, that using
```
$this->grav['assets']->add('https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML');
```
does not add the javascript as expected. That is a bug due to pathinfo which doesn't strip out the query of the asset.

Added 'enabled' option for summary and fixed query support in assets

---

system/src/Grav/Common/Plugin.php

While developing plugins I missed some really important functions again and again:
- There should be definetely a `disable` function doing right the opposite as 'enable'.
- I really like the idea of having global plugin configurations and page specific configurations. But since merging them together when needed is always a mess, I propose to add a `mergeConfig` function to the core functions. It will automatically load the plugins configurations merge them with the page header, returning back a new config data object. Usage in the plugin would be e.g.
```php
$config = $this->mergeConfig($page);
$option = $config->get('plugin_name.option');
```

Added merge config and disable function in "Plugin.php"

---

system/src/Grav/Common/Page/Page.php

Dear Andy,
according to the forum post "Blog always shows ‘Continue Reading’" I considered now all use cases and propose to add an additional option to toggle between looking for and ignoring summary delimiters. Together with the other summary options, we finally can adjust it for all our needs:
```
summary:
enabled: true | false       # enable or disable summary of page
format: short | long        # if set to long a summary delimiter
size: number                # positive number (set to zero to show 
```
In short the use cases are:
1. `summary.enabled: false` -- Switch off page summary (the summary is the same as the page content)
2. `summary.enabled: true`:
1. `summary.size: 0` -- No truncation of content happens except a summary delimiter can be found.
2. `summary.size: num` -- Content …

Added summary option

---

system/src/Grav/Common/Plugin.php

Dear Andy,
today I encoutered a minor bug in the **Plugin** class, that nested page overwrite default plugin configurations although some are not set. For example consider we have the follwing configuration in our YAML file (see e.g. my DropCaps plugin):
```
titling:
enabled: false              # Toggle to (de-)activate titling of text
first_line: true            # Highlight first line of paragraph
breakpoints: ".,:;!?'\"-"   # Specify which characters will end titling
```
We then want to enable `titling` in a page via
```
titling:
enabled: true
```
When using `$config = $this->mergeConfig($page)` we finally would expect to get
```
titling:
enabled: true     # <-- Changed via page header
first_line: true
breakpoints: ".,:;!?'\"-" 
```
but at the moment we get
```
titling:
enabled: true …
```

Fix to merge nested page options with default plugin configurations

---

system/src/Grav/Common/Page/Pages.php

Prevent a page from taken it's parent into account when detecting modified time.

fix for last modified time detection of page

---

system/src/Grav/Common/Markdown/ParsedownGravTrait.php

Hi @rhukster,
here is the PR of bugfix for issue https://github.com/getgrav/grav/issues/149 .

Changed Twig Link Regex which fixes #149 [Markdown Doesn't Handle [words](#)

---

bin/gpm
bin/grav
system/src/Grav/Common/Composer.php
system/src/Grav/Console/ConsoleTrait.php

To avoid the manual placement of composer into ``bin/``, this pull request proposes a centralised check for the availability of a global composer installation (and fallback to ``bin/composer.phar``).

Use global composer install when available

---

system/src/Grav/Common/Composer.php

My previous pull request #191 unfortunately had a small bug - the ``shell_exec`` call returned a string with an ending line break, thus breaking the command. Sorry for the trouble.

Fix composer location method

---

system/src/Grav/Common/Page/Pages.php

Hi @rhukster,
regarding our yesterday's chat, I prefer to add a new event `onBuildPagesInitialized` into core, to allow memory and time consuming plugins to be initialized only when it is really needed (e.g. a page has changed and therefore `onPageContentRaw` or `onPageContentProcessed` is triggered). Thus, when there are no changes the plugin isn't even initalized! This makes Grav (in my opinion) very powerful, since otherwise all plugins (even the time consuming ones) have to be initialized in the `onPluginsInitialized` event.
Ok, caching could be speed up the process. But not everything could be chached, i.e. when one can register additional classes and imho it would be the best, if even the caching (load and process data) should only happen, when there is actually some uncached pages. …

Add `onBuildPagesInitialized` event for memory & time consuming plugins

---

system/src/Grav/Common/Page/Page.php

This is a PR to allow custom summary texts for pages. The PR is fully-backward compatible, but now accepts integers (for limiting the length of a summary) and strings (to set the summary), e.g.
```php
// Sets the summary
$page->summary('My superawesome summary');
// Gets the summary with custom size (here: with length 15)
$page->summary(15);
// Or return summary with default settings
$page->summary();
```
Further, even if one sets a custom summary, it will respect the settings made in the [`system/config/site.yaml`](https://github.com/getgrav/grav/blob/develop/system/config/site.yaml#L15) file.

Modified `$page->summary()` to allow custom summary assignments

---

system/src/Grav/Common/Session.php

Call setcookie() after the session is started to refresh the session timeout. This prevents the session to end when the user is still active.

Refresh session timeout

---

system/src/Grav/Common/Page/Page.php

$parent->route() returned null when moving to the root

Fix moving the page to the root

---

system/src/Grav/Common/Page/Page.php

With Grav mult-language ability it becomes somehow necessary (or a nice to have feature) to know the language of the page. This becomes specially important for plugins, that set special language dependent routes or taxonomies.
This PR will add such a feature to core.

Add language property to page

---

system/src/Grav/Common/Config/Config.php
system/src/Grav/Common/Page/Page.php

This PR references https://github.com/getgrav/grav/issues/248. I further added a bugfix when calling `$page->summary` with system option `summary.enabled: false`.

Fix #248 (Plugin language interference) and fixed summary

---

system/src/Grav/Common/GPM/Installer.php

This change fixes an issue connected with https://github.com/getgrav/grav-plugin-admin/issues/80 that occurred when installing plugins removing the duplicate slash in the beginning due to https://github.com/getgrav/grav/blob/develop/system/defines.php#L17 .

Fix error from grav-plugin-admin issue # 80

---

system/blueprints/config/system.yaml

As of PHP 5.1.0 the character 'o' represents the ISO-8601 year number in a date format. Therefore the 'o' needs to be escaped to avoid being converted to a year in the admin > configuration > system > long/short date format pulldown menu.
I should note that this fixes the issue for English, but you might want to consider moving the date format options into a language string in order to provide better multi-language support.

Fix issue with date format for PHP 5.1.0+

---

system/src/Grav/Common/Page/Page.php

Fixes https://github.com/getgrav/grav-plugin-admin/issues/123
When a tag contains an apostrophe it's encoded and it cannot not match the page taxonomy items unless decoded.

Solve an issue with apostrophes in the taxonomy name

---

system/src/Grav/Common/Grav.php

The default config option is an empty array, which causes get() to return null, which can lead to an error with the type of the second argument to in_array().

Set default when config option is empty

---

system/src/Grav/Common/Page/Page.php

This change allows a plugin to call validate() (which in turn calls blueprints()) on a page from the front, without needing the admin plugin to be active and set in the Grav object.

Allow validating a page from outside the admin plugin

---

system/src/Grav/Common/Page/Medium/ImageMedium.php

This patch adds more support for responsive images, allowing you to do the following:
```
page.media.images|first.derivatives(320, 960, 100).sizes('(max-width: 26em) 100vw, 50vw').html()
```
This will output an image tag with srcset for all widths starting from 320px to 960px in steps of 100px, the image will never upscale. The example uses an image with an intrinsic width of 650px.
```
```
In the code you'll see we just remember a list of url and width, this has been done to avoid memory problems while using lots of steps.

Responsive image

---

system/src/Grav/Common/Language/LanguageCodes.php

Now nativeName for Russian is "Русский", not "русский язык".

Change nativeName for Russian language

---

system/src/Grav/Common/Assets.php

This PR adds the ability to set custom media attributes to CSS stylesheets via e.g. 
```twig
{{ do assets.addCss('theme://css/print.css', 100, null, 'print') }}
```

Add CSS media attribute

---

.htaccess

I'm sure my setup is pretty unusual, but as I was trying out Grav for the first time I was greeted by a Apache 403 Forbidden error whenever I tried to view the home page.
Turns out that I don't have the `DirectoryIndex` directive set, and it's easy enough to include in the .htaccess file. Looks like other CMSs, like Drupal, include it, so here it is if you want it.

Add default apache resource for index.php

---

system/src/Grav/Common/Config/Config.php
system/src/Grav/Common/Plugins.php
system/src/Grav/Common/Themes.php

This PR addresses a minor issue when dealing with custom multisite configurations using e.g. a `setup.php` and one changes the plugin folder location other than `user/plugins`. In this case the plugin language files aren't loaded correctly into the system. This PR fixes this.
**Update:** Ok, just added some other minor issues concerning loading of plugins and themes from different directories.

Load language files according to stream configurations

---

system/src/Grav/Common/Backup/ZipBackup.php

The back-up  function is a great feature and to allow Mercurial users to revision control their page files some more ignore directories like `.hg` were added.

Add a few more common RCS to ignore folders

---

README.md

add links directly to the tabs for plugins and themes on getgrav.org. The first time I loaded the main downloads page I didn't see the plugins/themes tabs because I immediately started scrolling down. It might be worth adding to the bottom of that main page a quick line to the tune of "Looking for plugins or themes? Click here or here."

add specific links to 'adding functionality' intro

---

system/src/Grav/Common/Twig/Twig.php

This patch passes the Page object down to the onTwigPageVariables event handler of a plugin so it can determine and manipulate the page headers of the corresponding page object. It is otherwise not possible to access page headers of modular pages because `$this->grav['page']` will point always to the main page not the modular subpage.
Refer to discussion here: http://getgrav.org/forum#!/getgrav/plugin-development:ontwigpagevariables-event-h::unread

onTwigPageVariables event handler gets Page object passed as Event parameter

---

system/defines.php
system/src/Grav/Common/Assets.php

Asset management uses now streams rather the constant ASSETS_DIR to configure location of pipelined asset files. In addition it supports sub-directories for assets location, for example `assets/runtime`.
The assets directory can now be re-configured changing the stream in `streams.yaml` Example:
```
schemes:
asset:
type: ReadOnlyStream
paths:
- assets/runtime
```

Asset management uses now streams rather the constant ASSETS_DIR

---

system/src/Grav/Common/Cache.php

If the asset directory was relocated using streams, clearCache would delete the wrong directory.

Use streams instead of hardcoded paths for clearCache()

---

system/src/Grav/Common/Page/Medium/ImageFile.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

Image default filters are called twice if `system.images.cache_all` is turned on and a _meta.yaml_ file exists, for example the default filter `enableProgressive` would is called twice in that case.
With `system.images.cache_all` enabled, on a page with a single image file the default filters are called once which would be correct.
Once a meta.yaml file is added to the folder (can be just an empty file) the default filters are run twice. This can be verified by logging the execution of the applyOperations() method
and also by dumping the Image object:  the operations array contains two elements.
This compromises performance for sites with lots of images and/or more complex filter operations
when the image cache is re-build.
This PR adds a clearOperations method and it is called when doing …

Clear previously applied operations when doing a reset on image files to avoid calling filters twice

---

system/src/Grav/Common/Page/Medium/ImageMedium.php
system/src/Grav/Common/Page/Medium/Medium.php

This commit adds the possibility to add inline style attributes to Medium objects and width and height attributes to ImageMedium objects. Usage is like shown below:
```
{{ page.media['myimg.png'].width().height().html }}   # use image's native dimensions
{{ page.media['myimg.png'].resize(100,200).width(100).height(200).html }}
```

Support for width/height and style attributes to media and image files

---

system/src/Grav/Common/Grav.php
system/src/Grav/Common/Page/Pages.php

This PR enables Grav to specify URLs with a trailing slash for a page, by means of a default route with a trailing slash.  Such a feature shall help migrating legacy sites to Grav while maintaining existing and well established URLs which may have trailing slashes.
Refer to https://github.com/getgrav/grav/issues/404
Example 
```
---
routes:
default: /support/
---
```
A request to this page will NOT redirect to `/support` and resolve as `/support/`
This feature works with `redirect_default_route` either on or off and if  `redirect_default_route` is on a request to `/support` redirects to `/support/` otherwise the page is served as is.
`redirect_trailing_slash` must be set to false for this use case for obvious reasons as this would conflict.

Added support for default routes with a trailing slash

---

system/src/Grav/Common/Assets.php

Just a little patch which prevents the generation of empty `<style>` or `<script>` tags in case the added inline JS or CSS was an empty string.
This saves to wrap addInlineJs calls into an if clause checking if the string is defined/empty or not on Twig level.

Don't create <style> or <script> tags for empty inline CSS or inline JS

---

system/src/Grav/Common/Themes.php

This PR fixes #432 and improves autoloading speed using `file_exsits($file)` instead of `stream_resolve_include_path($file)` for a file check.

Fixes #432 (Theme autoloading doesn't seem to work)

---

system/src/Grav/Common/Helpers/Truncator.php

The `Truncator`-class fails when the truncated text contains unicode characters with a nice exception:
"DOMDocumentFragment::appendXML(): Entity: line 1: parser error : Input is not proper UTF-8, indicate encoding ! Bytes: 0xC3 0xE2 0x80 0xA6"
By using the `PCRE_UTF8` modifier `u` everything is UTF8 and all is fine.

Use PCRE_UTF8 so unicode strings don't break up.

---

system/src/Grav/Common/Data/Blueprint.php

The English term "Validation failed:" was hard coded on line 83. Instead, I created a translation and placed this at /system/languages/en.yaml. It will need to be translated into other languages by others.

Added a translation for "Validation failed:" text

---

system/src/Grav/Common/Data/Validation.php

The English phrase "Invalid input in " was hardcoded at line 40. I created a new translation 'FORM.INVALID_INPUT' and placed it in /system/languages/en.yaml. It will need to be translated into other languages by others.

Added a translation for "Invalid input in " text

---

robots.txt

Prevent search engines from crawling and indexing unnecessary files and directories. The "/user/plugins/" directory may need to be added to the Allow list if plugins use frontend accessible assets. This is tested at a basic level using Google Fetch and Render.

Prevent crawling of unnecessary directories

---

system/src/Grav/Common/Data/Blueprint.php
system/src/Grav/Common/Utils.php

Moved field handling to a separate function and added logic to correctly process nested lists. 
Code diff looks way more complex than it actually is. Copied everything that originally was under `else if ($field['type'] !== 'ignore') {` into a new function, so that it can be called from multiple places.
Fixes https://github.com/getgrav/grav-plugin-admin/issues/273

Proper handling of list fields

---

system/src/Grav/Common/Config/Setup.php
system/src/Grav/Common/Service/ConfigServiceProvider.php

@mahagr made this PR to fix a problem introduced in this commit: https://github.com/getgrav/grav/commit/dd2ddfeb409baafc0bf7fed2a5c1f74b2bf8cae2 
The multisite subfolder example http://learn.getgrav.org/advanced/multisite-setup#quickstart-for-beginners was failing because $container was no longer available. Made a PR so you can review and tell me if this is an OK change or you want to revisit it.

Make $container available in setup.php

---

system/src/Grav/Common/Page/Medium/ImageMedium.php
system/src/Grav/Common/Page/Medium/Medium.php

The current implementation of the `url` function for page medium does not work when the grav root path contains regular expression characters (e.g. `+`).
This PR fixes this by escaping the grav root with `preg_quote`.

Escape graph root in page medium to work with special characters.

---

system/src/Grav/Common/Assets.php

If there are no collections you can get a "Invalid argument supplied for foreach()" without an empty default.

Prevent error if no collections present

---

system/blueprints/user/account.yaml

Added the PLUGIN_ADMIN.SECURITY constant instead. Will add this to the admin language files too.

Fixed hardcoded string "Security"

---

system/src/Grav/Common/Grav.php
system/src/Grav/Common/Markdown/ParsedownGravTrait.php
system/src/Grav/Common/Page/Medium/Medium.php
system/src/Grav/Common/Uri.php

Proposed fix for #541.
After reading http://stackoverflow.com/a/6998242 rawurldecode (and
rawurlencode) is better over urldecode/urlencode: "rawurlencode is the
way to go most of the time. It deals with the modern scheme for URI
components, where as urlencode does things the old school way, where +
meant "space."

Use rawurldecode and rawurlencode instead of urldecode/urlencode

---

system/src/Grav/Common/Config/CompiledBase.php

finalizeObject, which assigns the checksum to the Config object, was
never called after the cache was built.
So the checksum on Config was always empty.

Call finalizeObject on Config from loadCompiledFile() when cache is already built

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Session.php

PR for #553
Still needs testing on a remove server, do not merge yet.
Locally it works fine on Firefox and Safari, on HTTP or HTTPS, tested both scenarios. 
Chrome limits it working when using the "localhost" domain name, not when using other aliases, I believe it's a security limitation of Chrome.

Add secure and httponly parameters to sessions

---

system/src/Grav/Console/Gpm/InstallCommand.php

When installing packages with dependencies, the GPM tries to install them also if already installed. This PR avoids doing so, installing only missing packages.

Command line GPM: Avoid prompting to reinstall already installed packages

---

composer.json

As a developer, instead of ([as described in the docs](http://learn.getgrav.org/basics/installation#option-2-install-from-github))
```shell
$ git clone https://github.com/getgrav/grav.git
$ cd grav
$ composer install --no-dev -o
$ bin/grav install
```
I would like to be able to execute
```shell
$ composer create-project getgrav/grav my_new_grav_project
```
to bootstrap a new Grav project.
This PR includes the following changes:
- Change package type from `library` to `project`
- This ~~is needed to be able to execute the `composer create-project` command, and also~~[<sup>1</sup>](#issuecomment-168844993) fits better, in my opinion
- Add a `post-create-project` command which executes the `bin/grav install` command after project creation.
This has the following benefits:
- It is possible to …

Allow grav to be installed as a composer project

---

composer.json

As a follow up to #585, this PR adds a branch alias for the develop branch, see https://getcomposer.org/doc/articles/aliases.md#aliases
This allows developers to create new bleeding edge Grav projects with composer through the slightly nicer looking
```
$ composer create-project getgrav/grav ~/webroot/grav 1.x-dev
```
instead of 
```
$ composer create-project getgrav/grav ~/webroot/grav dev-develop
```
(which still will work)
:octocat:

composer.json: Add branch alias

---

system/src/Grav/Common/Utils.php

Ensure the Nonces generation works when REMOTE_ADDR is not the real user IP address.
Since the IP is just a part of the nonce string calculation, we can rely on HTTP_X_FORWARDED_FOR.
This change was prompted by trying to run Grav on Cloud9 which REMOTE_ADDR is a random load balancer generated IP, not the user's IP.

Fix nonces for proxied IPs

---

composer.json

However, it will still be installed in `vendor` as required by
`rockettheme/toolbox`

Remove ircmaxell/password-compat as it's intended to provide forward compatibility for PHP 5.4

---

webserver-configs/nginx.conf

Primarily going to be used for install script but it makes it more apparent that someone may need to change their root path.

Change user to USER - Easy to note replacement

---

webserver-configs/web.config

This should work for most IIS systems and Azure. 
Local versions of IIS tend not to validate URL's so no problems there (for the most part)
Azure IIS does validate and this should work with default Azure settings.

Fix for #612

---

webserver-configs/lighttpd.conf

Consider the following path: `/grav_path/user/pages/01.home/_about/profilepic.jpg`
The pattern `^/grav_path/(\.(.*))|(\.(.*)/)` will match `.home/_about/` and will therefore forbid access to this image.
If I understand it right, this pattern should prevent access to dot files. In this case, it should be fine to simply remove the right *or branch*.
Another note: the `lighttpd.conf` also contains the following rule:
```
$HTTP["url"] =~ "^/grav_path/(.git|cache|bin|logs|backup|tests)/(.*)" {
url.access-deny = ("")
}
```
I think this rule is redundant, because the other rule already catches all dotfiles?

fix lighttpd config

---

system/src/Grav/Common/Grav.php
system/src/Grav/Common/Twig/TwigExtension.php

The Twig `date` filter does not translate dates automatically for us.
This PR lets `|date()` translate the date based on the locale.

Translate dates automatically in Twig filter

---

system/src/Grav/Common/Uri.php

Return the base relative URL including the language prefix, or the base
relative url if multilanguage is not enabled

Add URI::baseIncludingLanguage()

---

system/src/Grav/Common/GPM/GPM.php
system/src/Grav/Console/Gpm/VersionCommand.php

If a blueprint has no version specified, it's not a GPM package, do not try to update it (CLI/Admin).
Introduces a check on `gpm: false` in the theme/plugin blueprint, and also avoid trying to update if no version is specified in the blueprint, which means it's not a package published on the GPM.

Fix local themes with same folder name (slug) as a theme published on the GPM

---

composer.json
system/src/Grav/Common/Twig/Twig.php

Client code can now use
`{{ a_date|localizeddate('long', 'short', grav.language.getLanguage) }}`
The extension is only loaded if translations are enabled in the system config.

Add twig/extensions to allow Twig dates translation

---

system/src/Grav/Common/Markdown/ParsedownGravTrait.php

As discussed in #736 It's possible to override default Parsedown processing if the new `tag` for existing `type` will be inserted into the array in higher position then the standard tag we want to override.

A way to override default Parsedown behavior

---

system/src/Grav/Common/Grav.php

Fix an issue in the Grav lang redirect. E.g. I call `/order/id:order-20160320-202557-668641/token:2mgb4D27S3`, if multilang is ON, and the lang is prefixed, Grav loads the page `/en/order/`, losing all the parameters and additional URL segments

Add params, query and fragment when redirecting to a language or default route

---

system/src/Grav/Common/Twig/TwigExtension.php

Now when the file is passed to the gist filter only that file will be displayed, not the whole gist.
Example usage:
```{{ gist("000000000000000000000000", "somefile.php") }}```
Backward compatible by the way.

Add ability to link to file on gist

---

system/src/Grav/Common/Cache.php
system/src/Grav/Common/Page/Page.php
system/src/Grav/Common/Plugin.php
system/src/Grav/Common/Utils.php

any 'frontmatter.yaml` file will be merged into the page header. 
With this approach, in the admin this will be merged in transparently and shows up as if it were in the page frontmatter itself, and then when you save, it is in fact saved back into the page.  
Doing anything else differently is going to be much more complex because we'll have to handle two ways of generating header data (one for admin ignoring this file, and one for frontend).  However it's not even that easy because this data is potentially cached, meaning we'll have to maintain two versions in cache, leading to possible inconsistencies.
This is a pretty advanced feature and would not be something that could be set via Admin so am not sure if this is a problem or not.
Also it is fine if you use **Expert** mode because …

This allows a frontmatter.yaml file to be included in a page folder

---

system/src/Grav/Common/Service/ErrorServiceProvider.php

Deleted Whoops aliases as they are in `Grav\Common\Errors` implemented. In this file are unusued

Deleted Whoops aliases

---

system/src/Grav/Common/Assets.php

Fixes an issue with files ending with a line comment, but no new line.
Also fixes (in a case I found) the already-seen JSMin fatal issue with
"Regex not terminated" error.

Make sure there's an end of line after each file added to the pipeline

---

system/src/Grav/Common/Assets.php

The way that absolute URLs get excluded during cssRewrite() doesn't cover all possible cases due to a incorrect CSS_URL_REGEX.
The current one
const CSS_URL_REGEX = '{url\([\'\"]?((?!http|//).*?)[\'\"]?\)}';
does only exclude absolute URLs that are not being wrapped inside quotes (single or double), see https://regex101.com/r/rN4sE9/1
A better one might look like this (see https://regex101.com/r/uB8zV6/1):
const CSS_URL_REGEX = '{url\([\'\"]?((?!([\'\"]?(http|//))).*?)[\'\"]?\)}';
I am not a regex pro, so I cannot exactly explain why this is correcter than the old one. Knowing that negative lookaheads are a pain to maintain, I prefer this patch as a solution. Since we're already handling data-URLs like this, I think it's only best to process accordingly with remote urls.
This matches all …

Fix absolute URLs in pipelined CSS

---

system/src/Grav/Common/Processors/InitializeProcessor.php

Refs https://github.com/getgrav/grav/issues/842

Load `session` prior to `uri` as the initialization of Uri does some session handling for the active language

---

system/src/Grav/Common/GPM/Remote/AbstractPackageCollection.php

When having multisite folders with different user folders and one installs a plugin or a theme, Grav always installs it in the "root" folders like `user/plugins` or `user/themes`.
This PR addresses the issue (cf. https://github.com/getgrav/grav-plugin-admin/issues/319) and fixes it with full backward-compatibilty and without any change to the Grav GPM package system.
However in the future I advise to use streams in the package system, which are resolved to the respective folders in the grav installs of the users. This PR is a step to this direction and (I guess) will be tackled in **Grav v2.x**.

Install plugins and themes in correct multisite folders

---

system/src/Grav/Common/Utils.php

As per https://getgrav.org/forum#!/chitchat:file-x-is-not-within-the `Utils::normalizePath()` truncates zeros out of the path. The minimal use case to produce the issue is
```php
echo Utils::normalizePath('/3/0/2/1'); // returns '/3/2/1'
```
The reason is the `empty($segment)` check, which returns true for `empty('0')` due to type casting. This is obviosly wrong, since a path segment consisting of '0' is definitely non-empty ;-).

Fix `Utils::normalizePath()` truncating zeros out of path

---

system/src/Grav/Common/Page/Collection.php

Related to https://github.com/getgrav/grav/issues/898
I can't find better way to remove it with DRY principle :expressionless:
With smaller code we need to check a value for each `$this->items` iteration.
Also it can be used with `PHP_INT_MAX` with previous version of this code.

Remove end date check if not specified (better 32-bit support)

---

system/src/Grav/Common/Page/Collection.php

This PR optimizes #902 according to the DRY principle. Now only two instead of three if conditions are needed in each loop and redundant code was removed.

Optimize PR #902

---

system/src/Grav/Common/Assets.php

I don't know if this is intentional, but the enabled `enable_asset_timestamp` settings is not respected for pipelined assets. Even if I disable this setting the cache key is always added.
I know why the cache key should be present due to browser cache invalidation of changes. However what I don't understand is then, why this setting currently only affects non-pipelined assets (see e.g. [Assets.php#L556](https://github.com/Sommerregen/grav/blob/4cec9851a1f51d78894ee2b5cab28570a3e343e8/system/src/Grav/Common/Assets.php#L556)).
This PR is for the lazy-man. Instead of opening an issue we can discuss it here or if this behavior is intentional, feel free to close it.

Respect `enable_asset_timestamp` settings for pipelined Assets

---

composer.json

Hello,
I had ext-zip requirement in composer.json due to ZipArchive Usage.
When ext-zip isn't install, bin/gpm doesn't work.
Do you have a check config script, same as Symfony when installing for first time ?
bye

add ext-zip requirement

---

system/src/Grav/Common/Assets.php
tests/unit/Grav/Common/AssetsTest.php

This PR is an enhancement of PR #906, where we have used the cache key as a stable key for pipeline generation. Now whenever an asset has changed the pipeline will be regenerated again. This is possible, because a modification time is added to each (local) asset. Remote assets are ignored so far, since it is difficult to actually retrieve a reliable modification time...

Feature: Better assets pipelining

---

system/src/Grav/Common/User/User.php

I have a feeling that this is too "simple" in that no user specific config is merged with other configs but i stayed away from doing that so that plugin developers can choose whether to use user based config (for example the login plugin redirect) or if the want to use overarching config.

Add user to config

---

system/src/Grav/Common/Twig/TwigExtension.php

This PR addresses https://getgrav.org/forum#!/general:hiding-certain-tabs-from-no and enhances the `authorize` Twig extension method with full backward-compatibility. Thus, it can be used as usual with
```php
authorize(['admin.super', 'admin.pages']);
authorize('admin.super');
```
or with the new changes with
```php
authorize([
'admin' => [
'super' => true
],
'site' => [
'user' => false
]
]);
```
which makes it possible to set access rights for tabs via blueprints as
````yaml
assets:
type: tab
title: Assets
security:
admin:
super: true
site:
user: false
fields:
...
```

Improved `authorize` Twig extension

---

user/config/system.yaml

Markdown Extra is incorrectly specified as `markdown_extra`, whereas it should be:
```
markdown:
extra: false
```

Fix system.yaml

---

bin/gpm
system/src/Grav/Common/Filesystem/Folder.php
system/src/Grav/Common/GPM/Installer.php
system/src/Grav/Console/Gpm/DirectInstallCommand.php

This allows for direct installation of a local ZIP package or a remote URL based ZIP package.  
This command is intended for testing or troubleshooting where you might want to install a particular version of a plugin or a theme.  
For example to install v1.0.1 of the **Cors** plugin:
```
bin/gpm direct-install https://github.com/getgrav/grav-plugin-cors/archive/1.0.1.zip
```
To install a local plugin:
```
bin/gpm direct-install /Users/bob/downloads/grav-plugin-archives.zip
```
This also works for Grav core, however, if you install a version prior to the introduction of `bin/gpm direct-install` you won't be able to use the command after you 'downgrade'
```
bin/gpm direct-install https://github.com/getgrav/grav/releases/download/1.1.4/grav-update-v1.1.4.zip
```
1. This command will not …

New `bin/gpm direct-install` command

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/GPM/Response.php

In some occasions we've noticed people unable to connect to GPM. After further investigations it turns out that on some systems (Windows only has been confirmed so far), the SSL certificate cannot be verified, causing GPM to fail (references: #1044, #1008 and potentially #850).
The to go solution is to disable the peer verification from `cURL` and `fopen`.
This PR adds 2 new optional system config: `system.gpm.verify_peer` (default: `true`) and `system.gpm.method` (default: `auto`).
When enabled, the SSL certificate gets verified by either fopen or cURL methods. If disabled the checks is skipped (this is not advised but might be the only viable solution for some people)
By default is set to `auto`. Auto automatically tests if the `fopen` mechanism is available and if it is gets used. …

SSL Verify Peer

---

system/src/Grav/Common/Page/Types.php

This PR fixes #1059 and allows themes not to have any `templates/modular` folder right now, if they don't provide modular templates either.

Check for modular folder in `Types::scanTemplates`

---

.htaccess

In some hosted or load balanced environments, SSL negotiation happens upstream. In order for Grav to recognize the connections as secure, you need to check for the 'HTTP_X_FORWARDED_PROTO' header.
I know @w00fz had concerns about header forging, and I don't see how this approach sidesteps that, but at least it's not in the Grav code itself. I'm open to adding some wording to the description, warning against any hazards. I don't know enough to know what the real risks are. In my case, I trust my provider to manage the SSL correctly. 
I hope I'm not wasting your time. I'm just trying to get `\Grav\Common\Uri` to natively generate `https` URLs. I just want to give back if it will help make things easier for future users. I've already created a Grav-specific page on my provider's wiki …

.htaccess change to detect HTTPS forwarding

---

system/config/media.yaml

Most of Excel family is there except for macro-capable xls in Office 2007. Tested and working to enable .xlsm file upload.

Adding xlsm to supported mime types

---

system/blueprints/config/system.yaml
system/src/Grav/Common/Session.php

It was discussed in #1085 
The default is to use a split session as before.
I will also create a PR for the admin plugin with these translations (en):
```
SESSION_SPLIT: "Split admin & front-end session"
SESSION_SPLIT_HELP: "By changing this field, your session will become invalid and you will be required to login again."
```

feat(admin): add setting to split admin and front-end session

---

system/src/Grav/Common/Errors/BareHandler.php
system/src/Grav/Common/Errors/Errors.php

* Introduces three levels of verbosity:
* 2: Full stack trace
* 1: Current Grav error page
* 0: Bare 500 response
* Backwards compatible
* If `verbosity` isn't set, then it looks at `display`.
* Otherwise, `verbosity` is taken *instead of* `display`.
* If accepted, I suggest marking `display` as deprecated for a release or two and documenting the change. 
* Adopting this approach will not break legacy installs. Not updating your config file results in zero change in Grav behaviour.
References Issue #1064 and closed PR #1089. Thanks!

Adding 'system.errors.verbosity' to eventually replace 'system.errors.display'

---

system/src/Grav/Common/Markdown/ParsedownGravTrait.php

This PR extends the API for Grav plugins to access the Parsedown parser directly. First it avoids an exception, when an index is set, but no block type `$type` exists in the array. And second it allows to register Markdown extensions, which don't have a marker (The built-in `code` block is such an example, where indentation yields formatting the paragraph as code).

ParsedownGravTrait `addBlockType` and `addInlineType` enhancements

---

system/src/Grav/Common/Page/Page.php
system/src/Grav/Common/Utils.php
tests/unit/Grav/Common/UtilsTest.php

Fixes #1114 by comparing size of `$content` against the summary size. If a `$content` is short and doesn't require a summary to be generated, return it's original form.

Don't truncate HTML if content length is less than summary size

---

system/src/Grav/Common/Taxonomy.php
system/src/Grav/Common/Twig/TwigExtension.php

Taxonomy.php - Function to get taxonomy item keys. See http://ami-web.nl/work for sample application (labels in project list).
Twig/Twigextension.php - Function to redirect page from twig.

functions added to taxonomy and twigextension

---

system/src/Grav/Common/Page/Media.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

Because of the changes in #1107, the keys of the image alternatives array is no longer the ratio, but rather the image width. We now make sure to calculate the ratio correctly and use the appropriate one when applying the image filters. This fixes #1136

Use correct ratio when applying image filters to image alternatives

---

CHANGELOG.md
system/src/Grav/Common/Page/Collection.php
system/src/Grav/Common/Page/Page.php
system/src/Grav/Common/Page/Pages.php

If the `intl` PHP extension is loaded, only these flags are available:
https://secure.php.net/manual/en/collator.asort.php. Otherwise, you can
use the PHP standard sorting flags
(https://secure.php.net/manual/en/array.constants.php)
[#1169](https://github.com/getgrav/grav/issues/1169)

Allow to override sorting flags for page header-based or default ordering.

---

system/src/Grav/Common/Page/Page.php

Allows to use commas in taxonomy terms.
Currently you need to encode it 4 times. This means that to target a "t3a, t3b" taxonomy term you need to use the URL: `/posts/tag:t3a%2525252C%25252520t3b`

Decode single taxonomy params

---

system/src/Grav/Common/Page/Page.php

Loading the page children before call modular on the Collection.
In order to view the complete example issue you can refer to [https://getgrav.org/forum#!/general:cant-get-modular-collectio](https://getgrav.org/forum#!/general:cant-get-modular-collectio)

Fix Page Collections problem with @page.modular

---

system/src/Grav/Common/Helpers/Excerpts.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

Allows for more precise control than the min-width, max-width and step parameters. As previously discussed in #1051.

Added ability to pass an array of explicit widths to ImageMedium#derivatives

---

system/src/Grav/Console/Gpm/UpdateCommand.php

After [coming up in the forum](https://getgrav.org/forum#!/general:error-after-updating-plugin), I've added a warning to the `gpm/update` command if it notices that a new Grav version is available. My understanding is that best practice is to `bin/selfupgrade` *before* `bin/update`.

Added warning to `update` command when new Grav version is available

---

CHANGELOG.md
system/src/Grav/Console/Cli/InstallCommand.php
system/src/Grav/Console/ConsoleTrait.php
system/src/Grav/Console/Gpm/InstallCommand.php

Refs 
- https://github.com/getgrav/grav/issues/1203
- https://github.com/getgrav/grav/issues/1202

Improve detection of home path. Also allow ~/.grav on Windows, drop ConsoleTrait::isWindows() method, used just for that.

---

system/src/Grav/Common/Data/Validation.php

if the input array looks like this: 
array('valA','valB') (not a keyed array)
The return result before my change was:
array(array('valA'),array('valB'))
The return result after my change is:
array('valA','valB')
(here is an example that got bug me: https://getgrav.org/forum#!/theme-development:no-select-multiple-in-backe)

fixed array handling

---

index.php
system/router.php

This is a slight reworking of the original #1218 PR that added a custom `router.php` to enable support via the built-in CLI command. 
This moves the router under `system/` folder and also provides an error if you try to use the built-in webserver without the router option.

Reworked PHP CLI router PR #1218

---

.gitignore

On my installation, the security.yaml file is located in user/config/ folder.

Updated gitignore for user/config/security.yaml

---

CHANGELOG.md
system/src/Grav/Common/Filesystem/Folder.php
system/src/Grav/Common/Utils.php

Fixes #635 use mv instead of rename as that does not support cross volume operations

---

system/blueprints/config/system.yaml
system/blueprints/pages/default.yaml
system/config/system.yaml
system/src/Grav/Common/Page/Page.php

This makes it possible to cache content, but always process twig. Useful for regular but especially modular pages. 
```
never_cache_twig: true
```
Enabling this will allow you to add a processing logic that can change dynamically on each page load, rather than caching the results and storing it for each page load.
This can be enabled/disabled site-wide in the `system.yaml`, or on a specific page.
This allows twig logic to be processed on every page load even if the page is a modular subpage.  This is similar to disabling the cache completely, however, cache is still used to store the regular content that has been processed by markdown, plugins, etc.  So performance is better than disabling the cache, but not as good as caching content+twig processing.
NOTE: This is not compatible with …

Added ability to never cache twig. 

---

system/src/Grav/Common/Page/Medium/Medium.php
tests/unit/Grav/Common/Markdown/ParsedownTest.php

See issue #1253 .
`![] (...)` now outputs `<img alt src="..." />`
Same for `image.html('', '')`
`image.html('')` would output `<img src="..." />`, same as before. At least it's now possible to choose if alt attribute should appear.

Provided empty alt if '' is supplied

---

system/config/system.yaml
system/src/Grav/Common/Processors/ConfigurationProcessor.php
system/src/Grav/Common/Utils.php

Basically this removes the default value from the `system.yaml` file and sets it based on the system `PARAM_SEPARATOR` constant if the value is not already set/overridden in user `system.yaml`.

Don’t set default param_sep, use system constant

---

system/src/Grav/Common/Language/Language.php

Resets the page_extensions value.
Useful to re-initialize the pages and change site language at runtime,
example:
```
$this->grav['language']->setActive('it');
$this->grav['language']->resetFallbackPageExtensions();
$this->grav['pages']->init();
```

Add Languages::resetFallbackPageExtensions

---

system/src/Grav/Common/Data/Validation.php

The function validateNumber only checks for numeric values, regardless of int or float contexts.
**By PHP isNumeric**
"42",
1337,
0x539,
02471,
0b10100111001,
1337e0,
"not numeric",
array(),
9.1
**Will evaluate respectively**
'42' is numeric
'1337' is numeric
'1337' is numeric
'1337' is numeric
'1337' is numeric
'1337' is numeric
'not numeric' is NOT numeric
'Array' is NOT numeric
'9.1' is numeric
Grav though does not support all value types for a variety of reasons. One being YAML Blueprint definitions, where it makes sense to make a new type value for a more specialized format. Specifically for numbers if a more advance number format it would make sense to make a new type for that number format.
YAML spec specifically allows both Integer or Float contexts. As seen in Grav the validate …

Fixing a minor bug in Number validation.

---

system/src/Grav/Common/Data/Validation.php

Discussed with @mahagr.
Saved YAML configs gave undesired extra parameter (!!float 1 for example) because floats were not being cast back to integers upon save. This was even true when the filterNumber function was giving back a correct parameter. filter_var from validateFloat was actually perserving the float variable type which the YAML engine perserved upon Yaml::dump.
This is a unconventional fix, but it is the simplest way to handle this edge case.

Fix for the blueprint fix.

---

system/blueprints/config/site.yaml

`vsmall` is an incorrect class, and it should presumably be `x-small` so that the field renders the same size as  "Delimiter", used in /admin/config/site. This is how it renders currently (on larger resolutions):
Creds to Ricardo for pointing it out on Slack.

Fix class for Config/Site "Default language"-field

---

system/blueprints/config/system.yaml

Fix class for both "Default ordering" and "Append URL extension".

Fix class for Config/System"Default ordering"

---

CONTRIBUTING.md

Since the team is now on Slack.

Invite users to join Slack instead of Gitter

---

system/src/Grav/Common/Assets.php

Fixes #1382
In this function, there are now three `if` clauses in a row without `else` and with the same action in their body. Could perhaps be refactored. For now, I've just added that third, making it look crowded :(

CSS pipeline rewrite URL fix for webserver root-based paths

---

system/src/Grav/Console/Gpm/DirectInstallCommand.php
tests/functional/Grav/Console/DirectInstallCommandTest.php

Add --all-yes and --destination options
Fix a problem where temporary package files will not be
cleaned upon command error.

Fix #1389 related to `bin/gpm direct-install`

---

CHANGELOG.md
system/src/Grav/Common/Language/Language.php

Fixes Safari sending the language code always with a locale (e.g. it-it
or fr-fr)

When determining language from HTTP_ACCEPT_LANGUAGE, also try base language only

---

system/src/Grav/Common/Assets.php
tests/unit/Grav/Common/AssetsTest.php

This pull request makes Grav's Asset Manager support '_inline_' as a new loading option for CSS and Js assets. It also tries to simplify things by extracting common code from addCss() and addJs() into a new helper function (though the same could still be done for output and pipeline functions).
[Inlining CSS](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery) and Js resources can speed up rendering, particularly over mobile networks. It is not always feasible to directly include assets into the template, for example, where Sass-complied CSS is used or where CSS or Js is imported from external sites to load fonts.
Enabling any CSS and Js asset to become inline makes it easy to optimize for speed and to reduce [flashes of unstyled …

Adding the ability to inline CSS and Js code via Asset Manager

---

system/src/Grav/Common/Page/Page.php
system/src/Grav/Common/Page/Pages.php

Addes both helper methods to `Grav\Common\Page` and Grav instance utility functions to `Grav\Common\Pages`.

Ancestor and Inherited functions for Page & Pages

---

CHANGELOG.md
system/src/Grav/Common/Themes.php

I stumbled across this minor issue, when trying to extend the base `user/accounts.yaml` configuration. It turned out that there were some edge cases, that `loadLanguages` [Themes.php#L256](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Themes.php#L256) was called, but `theme://` was actually not registered yet. This PR fixes this. It further allows now overriding the `user/account.yaml` file that will be shown in Admin plugin and allows to use the `theme://` scheme inside the actual theme itself via, e.g.
```yaml
streams:
schemes:
blueprints:
type: ReadOnlyStream
prefixes:
'':
- 'theme://blueprints'
```

Allow `user/account.yaml` overrides + implemented more robust theme init

---

system/src/Grav/Common/Page/Medium/VideoMedium.php

I implemented some methods to support basic features of HTML5 videos. I saw this pull request https://github.com/getgrav/grav/pull/1092 after. I have then adjusted to fit the requirement mentioned.
Example in Markdown :
`
`
Example in twig :
`
{% set header_image_media = page.media.videos|first %}
{{ header_image_media.loop(true).autoplay(true).controls(false).poster("/path/to/image").html() }}
`

Add more controls over HTML5 video attributes (autoplay, poster, loop, controls)

---

.htaccess
webserver-configs/Caddyfile
webserver-configs/Caddyfile-0.8.x
webserver-configs/htaccess.txt
webserver-configs/lighttpd.conf
webserver-configs/nginx.conf
webserver-configs/web.config

Hey All,
When looking into the current `.htaccess` file's URL rewrite rules, I noticed a couple small issues:
- Periods are not escaped when black listing specific files (e.g., `LICENSE.txt`), meaning that other files/folders are perhaps unintentionally blacklisted (e.g., `LICENSEatxt`; likely not really an issue in practice).
- The `.yml` file type extension is not black listed (although `.yaml` is), meaning files such as `/codeception.yml` are accessible via HTTP requests.
This pull request so far simply addresses these two specific issues, however the last issue above has bothered me in a broader way. In general, it is often preferable (from a security point of view) to use a white list instead of a black list when it comes to filtering things (e.g., firewall rules, sanitizing input to …

[WIP] Web Server Config URL Rewrite Rules White List

---

system/src/Grav/Common/Grav.php

It's small change, but still...
https://tools.ietf.org/html/rfc7232#section-2.3

ETag header should be inside double quotes

---

CHANGELOG.md
composer.json
composer.lock
system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Grav.php
system/src/Grav/Common/Helpers/Exif.php
system/src/Grav/Common/Page/Media.php
system/src/Grav/Common/Twig/TwigExtension.php

This works alone, but works best in combination with latest Grav Admin develop branch.  Basically this is disabled by default to ensure you don't unexpectedly get a bunch of generated meta.yaml files.
To enable, simply toggle the `media.auto_metadata_exif` in `system.yaml`.  Every time media is processed for a page this toggle is checked and if enabled, **and** if the file is a `image/jpeg` mimetype **and** if no existing `.meta.yaml` exists, then it reads the EXIF data, and saves the data to `sample-image.jpg.meta.yaml`.
You can then access these like any other meta data, for example:
```
{{ page.media['sample-image.jpg'].meta.camera }}
```
A sample auto-generated meta file can be seen here:
```
FileSize: 738508
MimeType: image/jpeg
height: 1440
width: 1920
aperture: f/5.6
camera: …
```

Added Exif + Auto generation of meta.yaml files

---

system/src/Grav/Common/Data/Validation.php

YAML parsing causes a fatal error if the field is not a string

<testing> Avoid validation on a YAML field, do not parse YAML

---

system/src/Grav/Common/Processors/RenderProcessor.php

Ensure that output modifications by subscribers to `onOutputGenerated` are picked up.
In contrast to 1.2.4, 1.3.0-rc.2 no longer recognizes output modifications applied by subscribers to `onOutputGenerated`.
In 1.2.4, output was rendered [in Grav.php via `echo $this->output;`](https://github.com/getgrav/grav/blob/1.2.4/system/src/Grav/Common/Grav.php#L133) after processing `onOutputGenerated` inside `RenderProcessor`.

Fix output handling in RenderProcessor

---

system/src/Grav/Common/Page/Page.php

Refs https://github.com/getgrav/grav-plugin-sitemap/issues/43

Remove unpublished pages from the translated languages, move into untranslated list

---

system/languages/en.yaml
system/src/Grav/Common/Twig/TwigExtension.php

This fixes the weird message that appears when the posting time equals the current date, for example if a user submits a comment and checks the time their comment was posted right away.
Will probably require the JUST_NOW variable to be added to all translations.

Nicetime fix: 0 seconds from now -> just now

---

system/src/Grav/Common/Page/Medium/ImageMedium.php
system/src/Grav/Common/Page/Medium/Medium.php

Strip backward-slashes from Medium.php's and ImageMedium.php's url() method, both ahead of and trailing the string. As this uses `trim()` and backward-slashes it should be safe across systems, because only Windows actually relies on them even though PHP will allow either forward- or backward-slashes in paths.
This solves [Admin 1119](https://github.com/getgrav/grav-plugin-admin/issues/1119). Tested with PHP PHP 7.0.7 and Grav from current source, on Windows 10 x64, using `php -S localhost:80 -t "C:\Users\Ole Vik\Downloads\Grav\develop" system/router.php` to run the server.

Fix Windows routing with built-in server

---

CHANGELOG.md
system/src/Grav/Common/Session.php

(Refs https://github.com/getgrav/grav-plugin-login/issues/121) 
We didn’t allow 0 as an expiry value for `setcookie` http://php.net/manual/it/function.setcookie.php.
If “remember me” is not checked, and the browser is closed AND it’s not set to continue your session (see https://stackoverflow.com/a/10772420/205039), the session will be cleared.
Remember: Admin has its own session lifetime setting in its configuration.

Allow to set `system.session.timeout` to 0 to clear session on browser close

---

system/src/Grav/Common/Page/Pages.php

When there are > 100 pages, on unix the sorting is not natural and so Grav orders 1-10, 100, 101 ...
Turns out the issue is caused by the `Collator` that we use for sorting when `intl` extension is available. `Collator` ([ref](http://php.net/manual/en/collator.asort.php))  does not support the `SORT_NATURAL` flag like the `sort` ([ref](http://php.net/manual/en/function.sort.php)) method does which is the reason this has never sorted naturally as expected.
Unzip [02.cats.zip](https://github.com/getgrav/grav/files/1136675/02.cats.zip) under your pages and load the frontend with and without the fix.
> Note: needs to be in linux
Fixes #1524

Fix natural sort when > 100 pages

---

system/src/Grav/Common/Page/Pages.php

[This](https://github.com/getgrav/grav/commit/287a51148a3cdc74d70f6dd9e1de0c3d336b8fae) appears to have broken page ordering (see #1574).
Test-information:
Did a quick test on a personal project, clearing cache and reloading
the page fixed the default sort order of the navbar (i.e. it displayed
according to numeric folder prefixes).

Fix default sort order

---

system/blueprints/config/system.yaml

In commit 08920d5 it was allowed to set `system.session.timeout` to be `0`.
But the admin plugin refused to save this value because of the defined validation rules.
To fix this issue I changed the min. value of the validation rule from 1 to 0. 
I'll be grateful if you could accept this PR.

Change field validation of `system.session.timeout` to accept `0`

---

system/src/Grav/Common/Page/Page.php

1. Calculate the string size without any html tags, so now you can get exactly what you wanted length;
2. Support utf8 2 character widths characters, like Chinese, Japanese;
3. This is a quick dirty mod, some associated functions should be rethinked;

Quick Fix Summary issues

---

system/config/system.yaml
system/src/Grav/Common/Grav.php
system/src/Grav/Common/Uri.php

A permanent redirect can not be changed remotely once it has been sent.
Permanent redirects (301 / 308) are exactly what the their descriptive
name suggest. A 301 or 308 will be indefinitely cached client-side,
sometimes even when a user clears their cache.
They should be used to keep search engine page rankings by sending a
permanent redirect on a page by page basis, not for site to site or
protocols (http to https).
Especially on a new Grav installation, the default should not be 301.
My reasoning is that with the first visit to a new installation, before
even doing anything else, the 301 is already permanently cached in the
browser.
Additionally, temporary redirects can be influenced remotely and are not
that expensive on the webserver nowadays with event-based handlers.

Changing back the default redirect code from 301 to 302.

---

system/src/Grav/Common/Language/Language.php

Here is my PR
A little for my poor english, a bit because I thought the solution was not exhaustive (the presence of the other two arguments: array_support and html_out) I hesitated to do this PR. I've done the tests I find necessary, I think it's okay  :smile:

fix Twig dynamic translation

---

system/src/Grav/Common/Page/Medium/ImageMedium.php

Since grav uses the GD Adapter of Gregwar/Image and has no option to change it, this should be safe to implement, when the latest Version of the Lib is used.

Gregwar/Image supports gaussianBlur, so should Grav

---

system/src/Grav/Common/GPM/Installer.php

My plugin [Admin Addon Revisions](https://github.com/david-szabo97/grav-plugin-admin-addon-revisions) has dashes in its name. That way the Installer is trying to load the `Admin-addon-revisionsInstall` class, which is impossible because class name can't contain dashes.
I added a second check which tries to load the alphanumeric version, in this it will try to load `Admin-addon-revisionsInstall` first, if it can't find it will try to load the `AdminaddonrevisionsInstall`.

Try to load alphanumeric Installer class

---

system/src/Grav/Common/Page/Page.php

No reason for this to be missing from the page object as it has isFirst and isLast, useful if you need access to the index of a modular within it's twig templating.

Added current position to page object

---

system/src/Grav/Common/Session.php

Because setting cookie twice bothers me. Now proper options are applied to first one, so no need to set it again.
`RocketTheme\Toolbox\Session` uses `ini_set()` internally anyway, so this should not be a problem, but it can be changed to full `session_set_cookie_params()` call.

Fix setting session cookie twice

---

system/blueprints/config/system.yaml
system/src/Grav/Common/Uri.php

Simple adjustment to allow case insensitive urls. 
The toggle shows up in the advanced section of the system options of a Grav site. 
I understand the admin plugin will also need an update to provide the label and help text.
Please let me know if this change requires additional development. I'm unsure if there are wider repercussions for this change.

Added system option to enable case insensitive urls.

---

system/src/Grav/Common/Session.php

While, as pull request #1634 has proven, it's not the best idea around to get rid of the duplicate session cookie, I still consider it a good idea to ensure that the initial cookie has properly configured security. Doing so not only prevents the so-far-distant scenario where a ~~poor JavaScript interpreter programmer~~ _mastermind visionaire_ makes the Set-Cookie HTTP headers visible to JavaScript unless they're set to HTTP only (or, worse yet, makes the Set-Cookie headers get processed alongside JavaScript, effectively making Grav suspectible to a while loop checking document.cookie), but also the imminent spread of FUD (which is probably happening yet behind our backs, see the first Google result for "Web Server Security Test", especially the grading penalty it gives for "missing secure …

Fix insecure session cookie initialization

---

system/src/Grav/Console/Gpm/InstallCommand.php

From cd816b67747b07c1c62cc3c05cad0571b581c5fb the method *Grav\Console\Gpm\InstallCommand::processPackage()* is invoked with 3 parameters while 1 or 2 are required.

InstallCommand::processPackage() invoked with 3 parameters, 1-2 required

---

system/src/Grav/Console/Cli/InstallCommand.php

why do I have to clone the entire history of the plugin?

Update Grav Console Cli InstallCommand.php

---

system/src/Grav/Common/Cache.php

Hello, i currently encounter a issue which are super danger if user accidentally remove assets folder. and run 'gpm install' on their machine. 
The findResource method will return false and `glob($path . '/*')` will return the whole directory of user's root disk, which will remove everything on your current disk. 
Here is a screen shot show how it looks like.
I know it's my fault, but it shouldn't broken my computer.

make sure find resource return valid path before clean the cache

---

CHANGELOG.md
system/src/Grav/Common/Assets.php

Had to make regex'es ungreedy. I think the same issue is in 
CSS_SOURCEMAP_REGEX
CSS_IMPORT_REGEX
HTML_TAG_REGEX (well, this seems to be used with a single `<script>` or `<style>` tag, but...

Fixed CSS Pipeline failing with Google remote fonts if the file was minified (#1261)

---

system/src/Grav/Common/Page/Medium/AudioMedium.php

Adds support for `autoplay`, `controls`, `loop`, and `preload` attributes of `audio` elements, with rudimentary validation for `preload`.
Functions for `autoplay`, `controls`, and `loop` are copied directly from pfcloutier-druide@aaa3f82
See also #1442.

Add additional controls to HTML5 audio attributes

---

tests/unit/Grav/Common/AssetsTest.php
tests/unit/Grav/Common/ComposerTest.php
tests/unit/Grav/Common/GPM/GPMTest.php
tests/unit/Grav/Common/Page/PagesTest.php
tests/unit/Grav/Common/UriTest.php
tests/unit/Grav/Common/UtilsTest.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertInternalType` and `assertNotInternalType` instead of `is_*` functions;
- `assertContains` instead of `in_array` function;
- `assertGreaterThan` for mathematical comparisons;
- `assertNull` and `assertNotNull` instead of strict comparison with `null` keyword;
- `assertTrue` instead of strict comparison with `true` keyword;
- `assertFalse` instead of strict comparison with `false` keyword;
- `assertArrayHasKey` instead of `isset` function;
- `assertSame` instead of comparisons `==` and strict comparisons `===`.

Refactoring tests

---

system/src/Grav/Common/Page/Page.php

Taxonomies with spaces were not recognized because they are encoded in the uri, but the taxonomy collection was not encoded.  So, they never matched.  It seems like a simple rawurlencode of the taxonomy string should allow them to be found.

Taxonomy Filtering - space characters

---

system/src/Grav/Common/Uri.php

Modified Build scheme and Build port functions to take into account those in SSL offloading situations.
An attempt to fix: Links not always HTTPS behind off-loaded SSL (AWS) #1827

Fix for #1827

---

CHANGELOG.md
system/src/Grav/Common/Debugger.php
system/src/Grav/Common/Grav.php

Right now debugbar gets turned off on all non-HTML pages. Unfortunately enabling debug manually is not ideal and does not even really work as all of the debug messages added before calling `enable(true)` (not to mention other data) get lost.
This update will make the Debugger class less dependent on the configuration as well as keeps the debugbar enabled all the time. If the response isn't in HTML, the output will just not be rendered by default but is available for the plugins/templates.

Make it possible to include debug bar also into non-HTML responses

---

system/src/Grav/Common/Config/Setup.php

I'm working on a custom install of Grav, where being able to dynamically swap setup files was required. I've modified the $file assignment to permit overriding it's value via a defined constant, "GRAV_SETUP_PATH".
And I thought that might be useful to others, so I'm submitting a pull request.

Add overriding of setup.php config file, via constants

---

system/src/Grav/Common/Page/Medium/Medium.php

When using a default image derivatives (#1979) setting like
images:
defaults:
derivatives: [300,600]
then Grav crashes when a video gets embedded.
The following error occurs:
rawurlencode() expects parameter 1 to be string, array given
system/src/Grav/Common/Page/Medium/Medium.php:521
This patch encodes array URL parameters correctly.

Do not crash when generating URLs with arrays as parameters

---

system/src/Grav/Common/Helpers/Truncator.php
system/src/Grav/Common/Utils.php
tests/unit/Grav/Common/UtilsTest.php

The original fix provided by #1125 in Utils::truncateHTML compared the
summary size with the full HTML string length.
Thus, the string was still being truncated (and the HTML rewritten) even
when only the HTML string length, and not the text length, exceeded the
summary size.

Move fix for #1114 to Truncator::truncateLetters

---

system/src/Grav/Common/Page/Medium/ImageMedium.php

Creating image derivatives currently keeps all the images in memory until the PHP interpreter is finished. With a substantial number of files or large images this can cause out of memory errors. I attempted to fix the issue by saving the image on disk immediately after the derivative has been created and then freeing it.
Processing large images still takes time. Ideally, multiple threads could be used to create the derivatives, if there is enough memory.
Please note that currently Gregwar\Image\Adapter\GD does not free the associated image resource on deallocation. I've created a [pull request](https://github.com/Gregwar/Image/pull/154) to fix this, too. (The checks don't pass because of a configuration error.)

Fix image memory use

---

webserver-configs/nginx.conf

nginx config offered in /webserver-configs does not work in recent distros. I have changed it to match the path of php7-fpm in Debian Stretch.

pointing fastcgi_pass path to match php7.0-fpm (on debian stretch)

---

system/config/site.yaml
user/config/site.yaml

It could be a bad idea to use default email addresses that could really
exist. Instead, use example.com, which RFC2606 defines as one of the
domains reserved for examples.

Use @example.com in default email addresses.

---

system/src/Grav/Common/Helpers/Truncator.php

truncateLetters now takes into account multibyte strings.
truncateWords doesn't seem to be affected : it correctly determines where word ends, taking utf-8 encoding into account.
Found 2 issues related : https://github.com/getgrav/grav/issues/1365 (closed) and https://github.com/getgrav/grav/issues/1737 (open).

Handle multibyte strings in Truncator (truncateLetters method)

---

system/src/Grav/Common/Page/Page.php

First of all, I am pretty new to grav and I'm pretty exited working with it. I come from the Drupal world and I love Grav because it's so similar it its concepts but still lightweight and way better to work with for smaller sites.
So pls give me a hint if I don't do this right here, it's my first contribution!
I started building a Plugin for automatic redirects when changing the folder's name in order to keep SEO ranking. To do that, I need to compare the original version with the current one when Saving a Page. Additionally I found it useful to check for the move action at this point, this way I don't need to compare the objects to see if something changes.
However, the _original property is private and cannot be accessed onAdminSave event.

Add getter methods for original and action to the Page object.

---

system/src/Grav/Common/Twig/Twig.php

This PR is related to the issue #1818.
This builds the modular template extension from the URI's extension (i.e. `http://examp.le/my-page.amp` or `http://examp.le/other-page.docx`).
It fallbacks to `TEMPLATE_EXT` const if URI extension is `null` or empty.
---
For my project : 
I'm creating an [AMP](https://www.ampproject.org) version of my website in the same theme.
my custom `system.yaml`
```yaml
...
pages:
...
types:
- html
- amp
...
```
So I have two template extensions : `.html.twig` for the regular pages and `.amp.twig` for the AMP pages.
I'm using the same content for the two versions.
If I create a modular page with the `.amp.twig`, Twig will load modular templates with the extension `.html.twig` (which will be wrong formated for AMP framework and not validated).

Modular template extension follows the master page extension

---

CHANGELOG.md
system/src/Grav/Common/Page/Pages.php
system/src/Grav/Common/Processors/InitializeProcessor.php
system/src/Grav/Common/Service/PageServiceProvider.php
system/src/Grav/Common/Session.php
system/src/Grav/Common/Uri.php
system/src/Grav/Framework/Session/Session.php
system/src/Grav/Framework/Session/SessionInterface.php

Fixes #1501 -- remember to add changelog entry on merge.
Replaces #1511 as the fix is now against Grav 1.5.

Fixed routing issues with multisite and multilanguage (Grav 1.5 edition)

---

system/src/Grav/Common/Config/ConfigFileFinder.php
system/src/Grav/Common/GPM/Installer.php
system/src/Grav/Common/Page/Pages.php
system/src/Grav/Common/Plugins.php
system/src/Grav/Common/Themes.php

`SplFileInfo::getFilename` returns the same value as `SplFileInfo::getBasename` (no arguments) while being locale safe (See #2083). For situations where `SplFileInfo::getBasename` needs to accept an argument, I would suggest implementing a `basename` helper function ([Good Example](https://github.com/cakephp/cakephp/blob/659a25db6d8013d5e187aec5bcfea47cdafa418f/src/Filesystem/File.php#L355)).

Change getBasename to getFilename where possible

---

webserver-configs/nginx-ddev-site.conf

DDEV:
> ddev is an open source tool that makes it dead simple to get local PHP development environments up and running within minutes.
This is a modified default ddev nginx configuration for GravCMS projects.

Added nginx config for hosting in a ddev project

---

system/src/Grav/Common/Page/Medium/VideoMedium.php

Fixes: #2099
To be able to add videos that behave as GIFs, two attributes are needed for the videos to be properly handled on iOS and in Chrome: muted and playsinline.
Muted
Chrome only allows videos to autoplay when the contain the muted attribute. Non-muted videos will not autoplay unless the user has interacted with the site. More details here:  https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#new-behaviors
Playsinline
The playsinline attribute allows developers to specify videos on iPhone should play inline and not automatically enter fullscreen mode when playback begins. More details here: https://webkit.org/blog/6784/new-video-policies-for-ios/

Add muted and playsinline attributes

---

system/src/Grav/Common/Utils.php

It seems to me that the current implementation of nounces are broken. Please read my commit messages as they should explain everything:
---
Remove deprecated "getNonceOldStyle" function
This commit removes the following functions:
- getNonceOldStyle
- generateNonceStringOldStyle
The functions have been replaced in newer versions of
grav. It seems to me that they only existed in order to make a
upgrade to a newer version of grav painless (i.e. accept both types of
nonce tokens). Nowadays, existing old style nonces are expired long
time ago so it should be save to delete the deprecated funtions.
---
Don't save nonces in static class variable
Currently, the behavior of `getNonce` is broken because it saves the
generated nonce in an array and only use the $action as the
key. However, the …

Fix broken nounce handling

---

system/config/media.yaml

Media type should be 'video' not file!
Have tested this on a local install and changing this line allows .webm files to successfully play.

fix .webm typo

---

system/src/Grav/Common/Processors/InitializeProcessor.php

When `system.pages.redirect_trailing_slash` is enabled, it's always a 302 even though `redirect_default_code` is set to something else. 
By removing it, it works as intended.

Remove hardcoded 302 when redirecting trailing slash

---

system/src/Grav/Common/Twig/Twig.php

When creating a theme that inherit from another theme one common thing is that you want to change a tiny thing in an existing twig file.
I couldn't find a good way to do that without copy the whole twig-file over to my theme. Which means that if the base theme update that twig-file I will never get the changes. And I couldn't figure out a way to reference the base theme twig file and override it at the same time.
So with this change I can change my theme config to something like this:
```
streams:
schemes:
theme:
type: ReadOnlyStream
prefixes:
'':
- user/themes/mytheme
- user/themes/quark
'quark/':
- user/themes/quark
```
And then if I want to update the footer in base.html.twig I can just create a base.html.twig file in mytheme that looks something like this:
```
{% extends …
```

Register theme prefixes as namespaces in twig

---

system/src/Grav/Common/Page/Medium/ImageMedium.php

Replaces any spaces in an image filename with %20 to avoid parse errors with the srcset attribute. i.e. changes:
srcset="image_path/grav_name320w.jpeg 320w, image_path/Original Name.jpg 2560w" to
srcset="image_path/grav_name320w.jpeg 320w, image_path/Original%20Name.jpg 2560w"

Small bugfix for responsive images

---

system/src/Grav/Common/Uri.php

* **What went wrong?**
I host some Grav websites in AWS EC2 instances behind AWS Cloudfront (to provide free SSL and caching). I do not have any ssl certificates installed in the EC2 instances (since Cloudfront handle it for us, such as a loadbalancer), so I actually have Cloudfront that handle HTTPS but communicates internally with the EC2 instance over HTTP. But, I recently figured out that Cloudfront does not provide the standard HTTP_X_FORWARDED_PROTO header but provide a HTTP_CLOUDFRONT_FORWARDED_PROTO header instead.
* **Resolution**
Adding the support of this header prior to REQUEST_SCHEME because Cloudfront provide it but with the value of the internal communication scheme (in my case http).
Auto build the port from the scheme when we are in this situation because Cloudfront does …

Added support for AWS Cloudfront forwarded scheme header

---

system/src/Grav/Common/Page/Page.php

When a field contain accentuated characters, reduce the risk of messing with it by passing unicode characters unescaped.
Twig will deal with them. And fewer backslash-escaping problems will arise.
In order to allow blueprints fields to contain Twig expression, `processString()` is used.
Ideally it would deal with object/array by processing (= Twig-rendering) inner elements recursively.
But what it instead does, in order to flatten the value, is `json_decode(Twig::render(json_encode($value)))`
If someone use such a field value: `{{ url.uri ~ 'é' }}`, it will be transformed to `{{ url.uri ~ '\u00e9' }}`.
And `Grav\Common\Twig::processString` calling `$this->twig->render()` with that string returns `localhostu00e9` whose accent won't be restored after `json_decode()`.
I don't know why Twig …

preserve accents in fields containing Twig expr. using unicode

---

system/src/Grav/Common/Page/Pages.php

UNTESTED!!
Happened to notice what looks like an unused parameter. Thought it would be nice to clean up the code a bit

Remove unused parameter

---

README.md

Provides a simple fix for a dead link to a resource on the README.MD 
+ 
Updated links to https links, since they're all https sites instead of http ones now.

fix dead link + add http > https changes to site urls

---

system/src/Grav/Framework/File/Formatter/CsvFormatter.php
tests/unit/Grav/Framework/File/Formatter/CsvFormatterTest.php

Haven't changed the original behaviour...
One thing that can be discussed, do we display header if they actually are numeric ? (I think for now yes, this is enforced by the test, but can be changed later)

Preliminary tests for CsvFormatter::encode + minor fix for empty data

---

system/src/Grav/Common/Utils.php

Added `getSubnet` util. To be used by Login Plugin for getgrav/grav-plugin-login#204

Add `getSubnet` util to Grav\Common\Utils

---

system/src/Grav/Framework/Cache/Adapter/MemoryCache.php

Use Null Coalesce Operator

---

system/src/Grav/Common/Uri.php

When using Grav behind an HTTPS-endpoint, we would probably have either one of
* `HTTPS=on`
* `X-Forwarded-Proto https`
Still, the latest virtualhost would still provide `REQUEST_SCHEME` which, contrary to HTTPS environment, would not be overriden (eg: Apache only creates `REDIRECT_REQUEST_SCHEME` with the requested value).
This change gives priority to non-empty `HTTPS` over `REQUEST_SCHEME`.

Privilegiate HTTPS environement over REQUEST_SCHEME

---

CONTRIBUTING.md

Replace with redirecting link to chat.getgrav.org, also link to forum again.

Remove Gitter, Slack

---

system/src/Grav/Framework/Uri/UriPartsFilter.php

Listening on an unix socket reports port number 0, which is interpreted as an invalid argument.
Same issue exists in vendor libraries used by Grav.
https://github.com/guzzle/psr7/pull/270
https://github.com/Nyholm/psr7/pull/115
One of them caused whole website to crash with HTTP 503 error, after updating from 1.5.8 to 1.6.3.
```
2019/04/15 12:06:33 [error] 22644#0: *15185375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Invalid port: 0. Must be between 1 and 65535 in /var/www/grav/html/vendor/nyholm/psr7/src/Uri.php:282
Stack trace:
#0 /var/www/grav/html/vendor/nyholm/psr7/src/Uri.php(178): Nyholm\Psr7\Uri->filterPort(0)
#1 /var/www/grav/html/vendor/kodus/psr7-server/src/ServerRequestCreator.php(252): Nyholm\Psr7\Uri->withPort('')
#2 …
```

Change minimal port number to 0 (unix socket)

---

system/src/Grav/Framework/File/Formatter/YamlFormatter.php

After tweaking my PHP configuration so that it would use the native YAML extension, I found out that `$decoded` can happen to be a string as well, causing the problems already mentioned in #2494. This ~~tiny, annoying and repetitive~~ pull request aims to correct that, hopefully for good this time. ¯\\\_(ツ)\_/¯

Make yaml_decode only return array, again

---

system/src/Grav/Common/GPM/Licenses.php
system/src/Grav/Common/Language/Language.php
system/src/Grav/Common/Page/Medium/ImageMedium.php
system/src/Grav/Common/Twig/TwigExtension.php
system/src/Grav/Common/Uri.php
system/src/Grav/Common/Utils.php
system/src/Grav/Framework/Collection/AbstractIndexCollection.php
system/src/Grav/Framework/Collection/ArrayCollection.php

"Get's" would either be the possessive form or a contraction of "Get is". Neither makes sense. 
"Gets" without the apostrophe would be okay in some replacements but just "Get" is fine.
This change will also correct the API docs. Thanks.

fixed typos in comments / API docs

---

system/router.php

Currently, if I want to use the `router.php` provided by Grav I need to start `php -S` in the Grav's root folder.
If on the production server, Grav is not installed at the documents root, this will make it slightly more complex to manage the assets.
This patch adds the option to start Grav as:
```sh
GRAV_BASEDIR="/grav" php -S localhost:8000 grav/system/router.php
```
(in this case it will also accept "grav" and "grav/" as the basedir values)

run route.php when grav is not at the root of the server

---

system/src/Grav/Common/Service/AccountsServiceProvider.php

Closes #2620 
Small check to allow accounts to prevent a constant being defined again. This allows `$grav['accounts']`  to be accessed multiple times when new `Grav::instance()` are created, for example when unit testing.

Check if GRAV_USER_INSTANCE constants are already defined

---

system/src/Grav/Common/Page/Page.php

Currently, when a collection is being parsed by `collection()`, it checks the filters, and based on them determines the value of the `$only_published` variable, which is then passed as the second argument to `evaluate()`. However, the mentioned `evaluate()` recursively calls itself, without passing the value of `$only_published`.
Because of this, every collection (or at least, every of them that I've tested with `collection()`) ends up being parsed as if the `non-published: false` filter had been applied, which might not be the case, drastically affecting the result of the evaluation. I therefore believe that the issue, hopefully correctly resolved in this pull request, should be assigned a fairly high priority.

Correct the evaluation of the non-published collection filter

---

system/src/Grav/Common/Taxonomy.php

Improves the naive implementation in #2596 and solves #1304, by allowing nested/hierarchical taxonomies. A helper-method recursively iterates through taxonomy fields.
The current one-level taxonomy mapping is kept as standard, but this allows nested setups to work alongside by reducing the taxonomy type to a dot-notation where necessary, and thus does not break `taxonomy.findTaxonomy()`. For example, a Page with this taxonomy defined in FrontMatter:
```yaml
taxonomy:
categories: academic
tags: [article, tufte, bogus]
author:
- name: "Helmut W. M. Sargeant"
email: "hwms@bogus.tld"
url: "https://www.stanford.edu/"
affiliation:
department: "Department of Literature"
organization: "Stanford University"
- name: "L. Agnes Prinn"
email: "lap@bogus.tld"
url: "https://www.yale.edu/"
affiliation: …
```

[RFR] Iterable Taxonomy

---

system/src/Grav/Common/Page/Page.php

Exception gets thrown when $this->header->metadata is not an array, added extra verification in order to make sure it is and array before doing array_merge()

fix exception array_merge() when $this->header->metadata is not array

---

tests/unit/Grav/Common/Markdown/ParsedownTest.php

When image cache is enable and you are trying to assert image from parsedown, the path is not the same as original but it's a generated one from cache
```
$this->assertSame('<p><img alt="" src="/subdir/tests/fake/nestedsite/user/pages/02.item2/02.item2-2/sample-image.jpg" /></p>',
$this->parsedown->text('![](sample-image.jpg)'))
```

[RFR] Fix cache image generation on parsedown assert

---

system/src/Grav/Common/Filesystem/Folder.php

If you ignore any "files" beginning with "." including directories, then the `all()` method will exclude `.somedir`, but not `.somedir/somefile`. Subsequently, when trying to copy all files returned from `all()`, it will fail when the `copy()` method tries to copy a file into a directory that has not yet been created because `.somedir` was omitted from the returned array of `all()`.
I found this bug when trying to install the admin plugin and `./tmp` was a mount and thus `rename()` failed and `self:copy()` was invoked instead (see lines 364-5).
Alternatively, the check at line 238 could be omitted altogether and all "." files and dirs would be copied. (I'm not familiar enough with the project to know why they were ignored in the first place.) 
Also, ignoring "." dirs and ALL their …

do NOT ignore "." dirs OR ignore "." dirs and all children

---

system/src/Grav/Console/Gpm/SelfupgradeCommand.php

Functions expects an array and not an package (was a bug before and annotation wasn't changed in the bugfix)

Correct download argument annotation

---

system/src/Grav/Common/Uri.php

Support for the X-Forwarded-Host

---

composer.json
composer.lock
system/src/Grav/Common/Browser.php

I maintain `donatj/phpuseragentparser` and recently released v1.0.0 😄 
It's entirely backwards compatible, but also adds a namespaced variant which is the prefered use. I have changed the code to point to that.
Everything else should continue to work as expected.
I have also added an object oriented wrapper should you wish to change to that. As is, this was simply the clearest route forward.
I am happy to answer any questions.

Updates donatj/phpuseragentparser to 1.0.0

---

system/src/Grav/Common/GPM/Response.php

We had problems installing a plugin (devtools) because when GitHub is redirected internally, "location" is written in lower case in the header.
According to RFC headers are case insensitive. So it's a bug in Grav.
See: https://code-examples.net/en/q/503ee1
I've adjusted the regex so that the installation works again with GitHub redirection.
See also:
https://regex101.com/r/R6AFdV/1

Fix: case-insensitive search of location header

---

system/src/Grav/Common/Page/Page.php

I am working on a website with a monospace font.
Using an ellipsis is more meaningful in general and a lot better looking in my particular case.

Use proper ellipsis for `summary()`.

---

system/src/Grav/Common/Page/Markdown/Excerpts.php
tests/unit/Grav/Common/Helpers/ExcerptsTest.php

This enables the option &noprocess to be expanded to &noprocess=id,hl
Example:
`[PlayStore](https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=de&target=_blank&noprocess)`
Current result link: `https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=de&target=_blank` - not opening in new tab
This will work as intended by not processing the `id`, however the target also gets no processed.
Using 
`[PlayStore](https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=de&target=_blank&noprocess=id)`
Will skip the `id` processing, and still process the target. Resulting in a better end result link.
New result link: `https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=de` - opening in new tab successfully
This is in reference to the following issues: …

added optional options to noprocess

---

system/src/Grav/Common/Config/Setup.php

This part should map the local ips to the name "localhost" to provide a single point for configurations. 
The feature was introduced in
https://github.com/getgrav/grav/commit/380b3be92812e71f9453d6ab15d100dd70588111
but should have never worked as the bug is already there.
Please check my change carefully as it seems to me as a potentially breaking change...

Fixed enviroment name mapping for localhost

---

webserver-configs/Caddyfile

Caddy 1 is officially deprecated in favor of Caddy 2. With that there are some changes to directives and such. I'm in the process of updating my blog site to use Caddy 2 over Lighttpd and the following changes seem to be OK. I'm not seeing any server-side or client warnings and/or errors but perhaps other users can confirm.
Official documentation on steps to upgrade, which I followed, are available [here](https://caddyserver.com/docs/v2-upgrade).
I noticed the original configuration listened on a network port vs. a unix socket in regards to `fastcgi` (I'm not sure if you want to keep this.)

Update to Caddyfile using Caddy 2 changes.

---

system/src/Grav/Common/Scheduler/Job.php

This enables running scheduled *shell* commands again because Symfony 4.2 deprecated passing commands as a string to the Process component: https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-process-commands-as-strings
One also needs to catch all possible exceptions from the Process component, though. These exceptions are never displayed or sent to any of the logs and I've spent hours trying to debug why my scheduled tasks are failing.
Fix should be applied to 1.6 and 1.7 branches.

Fix compatibility with Symfony 4.2 and up.

---

system/src/Grav/Console/Gpm/SelfupgradeCommand.php

Upgrading from a server within China was brutally slow. It couldn't update without timing out. This adds an option on the `selfupgrade` command to accommodate a timeout value for downloading the update.

Add option for timeout in selfupgrade command

---

system/blueprints/config/scheduler.yaml
system/src/Grav/Common/Scheduler/Scheduler.php

Since Symfony 4.2 passing chained shell commands to the Process component is not supported anymore and a working directory needs to be set by passing it as a completely separate parameter.
Unless somebody finds a way to use Process() for this and fixes it in the code, rework example custom job.
Related info: https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-process-commands-as-strings

Fix failing example custom job.

---

system/src/Grav/Common/Utils.php
tests/unit/Grav/Common/UtilsTest.php

As described in #3060 I changed the `checkFilename` function to check the exact extension.

Check exact extension in checkFilename utility

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Service/SessionServiceProvider.php
system/src/Grav/Framework/Session/Session.php

This patch allow to set `config.session.samesite` from system.yaml.
It does not set any default value, hence do not change the current behavior.

Allow to set SameSite from system.yaml

---

system/config/media.yaml

Fixed MIME types for .docx, .pptx and .xlsx for default media settings.
The wrong MIME types caused errors when redirecting to these types on mobile browsers.

Fixed MIME types in default media settings

---

system/src/Grav/Common/Page/Page.php

I've also verified this via code, the correct default is `false`. It is also documented here:
https://learn.getgrav.org/16/basics/grav-configuration#pages

Set twig_first setting to the correct default

---

system/src/Grav/Common/Page/Medium/ImageMedium.php

A very simple change that would make it possible to set the output format of an image from Twig / Markdown.
This would be particularly useful for being able to serve automatically generated webp images, created from jpegs.
Related to issue #1168

Added 'format' to magic actions for images - this will allow conversion and caching of webp images

---

system/src/Grav/Common/Language/LanguageCodes.php

That deleted second word literally means _language_, which is completely unnecessary in language choosing context (like for all other languages)

Fix Lithuanian nativeName

---

user/config/system.yaml

I think this value get overwritten anyways. Maybe we should remove it completely?

Set twig autoescaping to true

---

system/src/Grav/Common/GPM/GPM.php
system/src/Grav/Console/Gpm/IndexCommand.php

Third time's the charm (hopefully)
Adds ability to filter index results based on enabled/ disabled settings.

Added ability to filter enabled or disabled with bin/gpm index

---

system/src/Grav/Common/Page/Page.php

Flattr requires the `name` property instead of the `property` property in the meta tag. Added flattr as needle in the if condition.

Flattr requires name instead property.

---

system/src/Grav/Common/Page/Pages.php

In Grav 1.6.31, a collection like this:
```
items:
- '@root.descendants'
filter:
published: true
non-published: true
```
...catches all pages, published or not. This is thanks to the removal of inclusive sets before they are parsed.
It seems that sometime during the refactoring done in Grav 1.7, this removal of inclusive sets had gone missing. As a result, a collection like above first filters out non-published pages, then the published ones, and ends up empty. This pull request aims to fix that.
Bottom line, I think that this issue deserves a fairly high-priority fixing, as I'd imagine that [this](https://github.com/newbthenewbd/grav-plugin-tinymce-editor/issues/25) isn't the only workflow around that it is capable of breaking...
Thank You!

Fix removing inclusive filters in getCollection

---

system/src/Grav/Common/Themes.php

Currently when inheriting a theme and creating language files in the child theme, they will override the language files of the base theme. There is no chance to extend from the base theme language files other than copying them. This leads to a lot of manual syncing effort when updating the base theme.
```
themes
- child-theme
-- languages.yaml
- base-theme
-- languages.yaml <- content never loaded
```
I changed the language file loading to read language files from all themes in `theme://`.
This might be interesting for @lazybadger.

read all language files from theme stream

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Assets/BaseAsset.php
system/src/Grav/Common/Assets/Css.php
system/src/Grav/Common/Assets/Js.php
system/src/Grav/Common/Assets/Pipeline.php

Having the website pre-generated and hosted on a CDN, I would like to have integrity hashes included in CSS and JS assets.
This PR will allow:
* User to set if wants the integrity hash to be generated and added to their <script> and <link> elements
*  controlled via new `system.assets.enable_asset_sri` config option
* When true, this option will generate the integrity hash and add it to both pipelined and not pipelined assets

Add SRI integrity hash to assets

---

system/src/Grav/Common/Page/Markdown/Excerpts.php
tests/unit/Grav/Common/Markdown/ParsedownTest.php

There are 2 issues in `grav/common/page/markdown/Excerpts::processMediaActions()` that prevents the `loading` attribute for images to be set properly in Markdown.
1. Line 281: `$defaults = $config['images']['defaults'] ?? [];`
Config settings are not picked up.
- Should be `$defaults = $this->config['images']['defaults'] ?? [];`
2.  Line 284: `if (!array_search($method, array_column($actions, 'method'))) {`
`array_search` returns (in above use) an `int`, or `false`. When value is found at position `0` the negation will return `true` and hence, explicit value set in Markdown will be overridden by value from config.
- Should use strict comparison: `if (array_search($method, array_column($actions, 'method')) === false) {`

Fix Markdown image attr. 'loading'

---

system/src/Grav/Common/Flex/Types/Pages/PageCollection.php
system/src/Grav/Common/Flex/Types/Pages/PageIndex.php
system/src/Grav/Common/Page/Collection.php
system/src/Grav/Common/Page/Interfaces/PageCollectionInterface.php
system/src/Grav/Common/Page/Pages.php

While testing dateRange filtering for collection, I encountered error when the start value is not specified (see #3345 for the issue).
After looking deeper in the source code, I found that the method dateRange() come from an interface and has three implementations and the fix I submited in the issue was not complete. That's why I submit this pull request.
I've divided the fix into three commit so you may discard some of them :
* First commit deal only with the fix of behaviour and touch only minimum lines of codes,
* Second commit simplify a little bit the code,
* Third commit is about the interface (method definition) : using null instead of false (as the behaviour is not specified if you pass true`), updating the documentation of the code (and synchronize the documentation accross all …

daterange - allow optionnal start date

---

system/src/Grav/Common/Media/Traits/ImageMediaTrait.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

This is my first-ever fork, edit and PR on GitHub, I sincerely hope I did it right!
Thanks!

Adding the addFrame method to ImageMedium

---

system/src/Grav/Common/Page/Collection.php

Lets us have a workaround for #531
Also was [a discussion on Discourse](https://discourse.getgrav.org/t/page-prevsibling-nextsibling-inverted/17248/17)
This new method would allow to have expected (not inversed) `prev` and `next` items of the collection in Twig
Eg.:
```twig
{% set collection = page.parent.collection({items: '@self.children', filter: {published: true, routable: true}}) %}
{% set isFirst = collection.isFirst(page.path) %}
{% set isLast = collection.isLast(page.path) %}
<section>
{% if not isFirst %}
{% do collection.setCurrent(page.path) or collection.prev %}
<a href="{{ collection.current.url }}">Previous page</a>
{% endif %}
{% if not isLast %}
{% do collection.setCurrent(page.path) or collection.next %}
<a href="{{ collection.current.url }}">Next page</a>
{% endif %} …
```

Add `setCurrent()` method to Page Collection

---

system/config/media.yaml

mime type should be `audio/aiff`
reference: https://en.wikipedia.org/wiki/Audio_Interchange_File_Format

fix typo mime type of `.aif`

---

system/config/media.yaml

new image format developed by google
references:
https://codelabs.developers.google.com/codelabs/avif#0
https://caniuse.com/avif
@rhukster Is `type: image` automatically processed? If yes and there is no additional check for supported image formats it may cause issues. The support for `avif` by `gd` is not yet available. Maybe with php8.1.

add mime for `.avif` image format

---

.github/workflows/tests.yaml

now released https://www.php.net/releases/8.1/en.php

add php 8.1 to test

---

system/src/Grav/Common/Twig/Extension/FilesystemExtension.php

The complete file uses `filename` as variable name so I changed the variants.

Minor rename and documetation fix

---

system/src/Grav/Common/Page/Medium/MediumFactory.php
system/src/Grav/Common/Page/Medium/VectorImageMedium.php

Read images sizes from vector files to be more consistent with "photo" images.

Add Vector image auto_sizes support

---

system/src/Grav/Common/Backup/Backups.php

Same name both times, so it is overwritten in the same line

Remove variable duplicate

---

.github/workflows/build.yaml
.github/workflows/tests.yaml
.github/workflows/trigger-skeletons.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

webserver-configs/nginx.conf

I've had to manually change this on recent installs on Debian Ubuntu and Arch. All php-fpm packages (That I have observed) create a generic php-fpm.sock file which symlinks to the latest installed PHP version. 
PHP 7.X is EOL so I believe this should be a trivial change.

Update php-fpm socket file to use generic socket file

---

system/src/Grav/Common/Helpers/LogViewer.php

By making the date match group non-greedy, and escaping the dot between the logger and level match groups, the regex behaves better for log entries that contain square brackets and colons.
See #3683 for full bug report.

Fix LogViewer regex to reduce greediness, closes #3683

---

system/src/Grav/Common/Scheduler/Scheduler.php

Passing process as a string is deprecated since Symfony 4.2.

Fix whoami command usage

---

system/src/Grav/Common/Assets/Pipeline.php

This is a suggested fix for the issue mentioned in issue https://github.com/getgrav/grav/issues/3749
When using css imports using syntax `@import 'mystyle.css';` the url is not being rewritten.
- adapts the regex used to include above syntax.
- adapts method `Pipeline::cssRewrite()` to the newly added matches found by the regex.
The code has been tested on the following use-cases in */user/themes/quark/css/custom.css*:
```
@import 'import-using-string.css';
@import url('import-using-url.css');
h3 {
background-image: url('../assets/background-url-quotes.png');
background-image: url(../assets/background-url-noquotes.png);
}
```
All urls are correctly rewritten.

Fix url of @import not being rewritten

---

system/src/Grav/Common/Inflector.php

It's day 2 of learning Grav. I noticed the ordinalize example wasn't working on the docs https://learn.getgrav.org/17/themes/twig-tags-filters-functions/filters#ordinalize 
I almost understand 0.1% of the code, but it feels right.

Make Inflector::ordinalize() work

---

system/config/security.yaml
system/src/Grav/Common/Utils.php
tests/unit/Grav/Common/UtilsTest.php
webserver-configs/Caddyfile
webserver-configs/Caddyfile-0.8.x
webserver-configs/htaccess.txt
webserver-configs/lighttpd.conf
webserver-configs/nginx.conf
webserver-configs/web.config

Hi,
here are a few changes to improve the security for dangerous extensions.
- add several new dangerous extensions in `system/config/security.yaml`
The new `ph*` extensions are just a precaution. The `shtm*` extensions are a real thing and prevents that an attacker can upload html files which get rendered by the browser.
- make `Utils::checkFilename()` extension check case insensitive
- update webserver configurations

Improve security for dangerous extensions

---

system/src/Grav/Common/Scheduler/Scheduler.php

Added extension to the isCrontabSetup method to detect external triggers of the scheduler, so that in the admin interface the error message is hidden when the scheduler is called by an external trigger as discussed in #2647

Added detection of external triggers of the scheduler

---

system/src/Grav/Common/Flex/Types/UserGroups/UserGroupObject.php

This happens with discord oauth, possibly others

Fix invalid input to foreach

---

system/src/Grav/Common/Page/Markdown/Excerpts.php
system/src/Grav/Common/Uri.php

Keep encoded links encoded. With this PR markdown like this: 
```
```
Will result in:
```
```
Instead of not: 
```
```
See also issue  #1622

fix whitespace encoding in urls

---

system/config/site.yaml

Corrected blog: route: '/blog' comment from system.blog.route to site.blog.route

Correcting comment about custom site.yaml value

---

system/src/Grav/Common/Flex/Types/Pages/PageIndex.php

https://github.com/getgrav/grav/issues/3657
The following methods from the  Grav\Common\Flex\Types\Pages\PageIndex object do not work as expected in Admin. 
* public function ofType($type)
* public function ofOneOfTheseTypes($types)
* public function ofOneOfTheseAccessLevels($accessLevels)
1. Grav CMS v1.7.37.1
2. PHP 7.4
1. Load the Pages Collection of type 'default’ in the admin using the following code `$grav['flex']->getCollection('pages')->ofType('default’)`
The collection `Grav\Common\Flex\Types\Pages\PageCollection` is loaded with all the pages of a type ‘default’. 
`Too few arguments to function Grav\Common\Flex\Types\Pages\PageCollection::ofType(), 0 passed in grav-cms/system/src/Grav/Framework/Flex/FlexIndex.php on line 489 and exactly 1 expected`

Fixed too few arguments exception thrown in the admin with using flex objects

---

CHANGELOG.md
system/src/Grav/Common/Page/Markdown/Excerpts.php
system/src/Grav/Common/Uri.php

Reverts getgrav/grav#3719
The code change from getgrav/grav#3719 introduces a breaking change (as in, literally breaking) and throws a fatal error.
Culprit code:
```php
$excerpt['element']['attributes']['src'] = str_replace(' ', '%20', $excerpt['element']['attributes']['src']);
```
This lacks sanity checks around the src presence under attributes, which throws a fatal error `Undefined array key "src"`.
/cc @dirkjf - Please recreate the PR with adequate checks and unit testing so we don't run into this again, thanks!

Revert "fix whitespace encoding in urls"

---

system/config/media.yaml

Adds support for vCards (.vcf files) in case of e.g. scanning a qr-code with the direct url to the file, so that it can be downloaded. 
Only a thumb-vcf.png should be added then too.

Adds mime type for vCards (.vcf files)

---

system/src/Grav/Common/Utils.php

When a user adds an empty or otherwise invalid link in a page in markdown for example [](https://) and that page is parsed to be shown in a blog listing page that blog listing page crashes with a CRITICAL error. Instead of throwing an error the URL is now ignored. See also https://discord.com/channels/501836936584101899/506916956637495306/1185616779486167141

Allow empty and malformed links in markdown

---

system/src/Grav/Common/Scheduler/Job.php
system/src/Grav/Common/Scheduler/Scheduler.php
tests/unit/Grav/Common/Scheduler/JobTest.php
tests/unit/Grav/Common/Scheduler/SchedulerTest.php

This PR follows #3770 and adds an `outdated` option to the scheduler command.
This allows the scheduler to run jobs that should have been processed earlier but did not (use cases : server downtime, cron not running every minute).
``` bash
php bin/grav scheduler --outdated
```
First of all if you have another idea for the option name I'm open to discussion, I don't think `outdated` is really relevant.
Now the main concern :
While working on this feature I realized the Job `creationTime` is not stored in the config, but rather set when instantiating the job. The logic I had in mind involved checking if the job had been created later than the previous scheduled execution, to prevent running a job before its first scheduled run.
https://github.com/getgrav/grav/commit/4bb4069f5f92d1c149356c0496 …

[Draft] [Scheduler] Added 'outdated' option to scheduler command

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Media/Traits/ImageDecodingTrait.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

The decoding property of the HTMLImageElement interface provides a hint to the browser as to how it should decode the image. More specifically, whether it should wait for the image to be decoded before presenting other content updates or not.
With this trait you can add the decoding attribute to load images in an easy way. It basically works the same way as the 'loading' attribute (see [Grav Docs](https://learn.getgrav.org/17/content/media#loading)), with `async`, `sync` and `auto ` options. More info in [Mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding)

New Trait for decoding attribute in images

---

composer.json
composer.lock

`symfony/service-contracts` was never used.

fix(composer): remove unused dependency

---

system/src/Grav/Common/Page/Page.php

Added support to [Fediverse Creator meta tag](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/)

Support to Fediverse Creator meta tag

---

system/blueprints/config/system.yaml
system/config/system.yaml
system/src/Grav/Common/Media/Traits/ImageFetchPriorityTrait.php
system/src/Grav/Common/Page/Medium/ImageMedium.php

The fetchPriority property of the HTMLImageElement interface represents a hint given to the browser on how it should prioritize the fetch of the image relative to other images.
The fetchPriority property allows you to signal high or low priority image fetches. This can be useful when applied to <img> elements to signal images that are "important" to the user experience early in the loading process.

New Trait for fetchPriority attribute in images

---

.github/workflows/tests.yaml

- php versions should be strings
- caching updated to current recommendation
- fixed env var name
- https://github.com/shivammathur/setup-php/tree/2.31.1?tab=readme-ov-file#github-composer-authentication
- https://github.com/shivammathur/setup-php/tree/2.31.1?tab=readme-ov-file#cache-composer-dependencies
- related to #3865

chore(ci): update GH Actions php test
